### DISCUSSION TITLE
[Idea] Add a phpMyAdmin service to Docker compose file in order to easy access BO

### DISCUSSION THREAD

**Discussion by tesshsu** [PrestaShop/PrestaShop#32425] [Ideas]
### The problem

If we install by docker we could simply start, but once we want to dig into the database part, or to try to query some complex sql query then even in BackOffice it is slow and difficult
We might also use docker to see some tables by mysql command line for example:
docker run -d --name phpmyadmin -e PMA_HOST=<mysql_container_name_or_ip> -p 8080:80 phpmyadmin/phpmyadmin

But it is not as easy and as convenient compared using phpMyAdmin

My suggestion is to add the phpmyadmin service in docker-compose.yml file and add this part in the document, why phpMyAdmin ? phpMyAdmin is a web-based database management tool that is specifically designed to work with MySQL and MariaDB database systems. It uses the MySQLi extension and provides a graphical user interface for managing databases, tables, columns, indexes, users, permissions, and more. I think most php developer use phpMyAdmin so this could be adoptable if we add this service

### The solution

Here is my solution:

Only add extra phpmyadmin service in the docker-compose.yml file

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: prestashop
    ports:
      - "8080:80"
    restart: always

After all, here is my docker-compose.yml file:
```
version: '2.1'

volumes:
  db-data:
  vendor:
  var:

services:
  mysql:
    image: mysql:5
    ports:
      - "3306"
    mem_limit: 1024m
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
      MAX_EXECUTION_TIME: 1200
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: prestashop
    ports:
      - "8080:80"
    restart: always
  prestashop-git:
    build:
      dockerfile: .docker/Dockerfile
      context: .
      args:
        - VERSION=${VERSION:-8.1-apache}
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    environment:
      DISABLE_MAKE: ${DISABLE_MAKE:-0}
      PS_INSTALL_AUTO: ${PS_INSTALL_AUTO:-1}
      DB_PASSWD: ${DB_PASSWD:-prestashop}
      DB_NAME: ${DB_NAME:-prestashop}
      DB_SERVER: ${DB_SERVER:-mysql}
      DB_PREFIX: ${DB_PREFIX:-ps_}
      PS_DOMAIN: ${PS_DOMAIN:-localhost:8001}
      PS_FOLDER_INSTALL: ${PS_FOLDER_INSTALL:-install-dev}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN:-admin-dev}
      PS_COUNTRY: ${PS_COUNTRY:-fr}
      PS_LANGUAGE: ${PS_LANGUAGE:-fr}
      PS_DEV_MODE: ${PS_DEV_MODE:-0}
      ADMIN_MAIL: ${ADMIN_MAIL:-demo@prestashop.com}
      ADMIN_PASSWD: ${ADMIN_PASSWD:-Correct Horse Battery Staple}
    command: ["/tmp/wait-for-it.sh", "--timeout=60", "--strict", "mysql:3306", "--", "/tmp/docker_run_git.sh"]
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html:delegated
```

And then once docker-compose up

Here is the docker with phpmyadmin container :
![3](https://user-images.githubusercontent.com/3927152/235911216-b1962ca0-8edd-4119-90fd-90ae2386272e.png)

Here is link to phpMyAdmin with port 8080:
![1](https://user-images.githubusercontent.com/3927152/235911239-04c58c92-3fa4-473f-8be9-99e4ed4f4ead.png)

### Alternatives

Beside that I suggested add MAX_EXECUTION_TIME, mem_limit in MySQL service:
mem_limit: 1024m
MAX_EXECUTION_TIME: 1200

Increase the MAX_EXECUTION_TIME value, this could avoid if server takes a long time to start up
Increase the memory limit: this also could avoid server run time out since Prestashop had more large volume database

### Do you plan to work on this subject?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.
