### DISCUSSION TITLE
Error in symfony forms example module.

### DISCUSSION THREAD

**Discussion by nukdokplex** [PrestaShop/PrestaShop#33686] [Q&A] [answered]
There is error in both demo symfony forms modules:
`The controller for URI "/modules/demosymfonyform/configuration" is not callable: Controller "PrestaShop\Module\DemoSymfonyForm\Controller\DemoConfigurationController" does neither exist as service nor as class.`

So I really need to know how to create configuration controller for my module and add it to routes.yml properly.

**Comment by boherm** [comment]
Hello @nukdokplex!

Do you use the PrestaShop version in develop branch?

We haven't yet upgraded the codebase on demo modules for the develop branch version.
Anyway, you can declare your controller as service in the `config/services.yml` of the module.

You can create a `controllers.yml` file like so:
```yml
services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: true
    tags:
      - { name: !php/const PrestaShopBundle\Controller\Admin\FrameworkBundleAdminController::PRESTASHOP_CORE_CONTROLLERS_TAG }

  PrestaShop\Module\DemoSymfonyForm\Controller\DemoConfigurationController: ~
```

And add, at the top of `services.yml` few lines to import this `controllers.yml` file:
```yml
imports:
  - { resource: 'controllers.yml' }
```
