### DISCUSSION TITLE
Multistore configuration form, how to retreive the current context when building the form?

### DISCUSSION THREAD

**Discussion by jtraulle** [PrestaShop/PrestaShop#36066] [Q&A] [answered]
Hello :wave:,

I have read [Configuration forms in multistore context](https://devdocs.prestashop-project.org/8/development/multistore/configuration-forms/) documentation page and experimented with the `demomultistoreform` [example module](https://github.com/PrestaShop/example-modules/tree/master/demomultistoreform).

I would like to know if it is possible to disable a field of the form if not in a specific shop context.

The traditional behaviour is that by default, when `multistore_configuration_key` is defined in the `options` array of the FormBuilder add() method, the value of the field can be defined for all shops, overriden for a specific group of shop or for a specific shop.

I would like to be able to disable the field when in **all shops** or **group of shops** context to force the user to select a specific shop to be able to fill out the form field.

The purpose is to store a configuration value that is specific to a shop and that should not be allowed to be defined for a group of shops or all shops context.

How can I retreive the current context from within the `buildForm()` method of a class that extends CommonAbstractType ?

Thanks for your help :pray:

**Comment by jtraulle** [comment]
Maybe @matks ? Do you know if that's possible or not :innocent: ?

For now, I just discard any value when not in shop context and print a help text to instruct to select the shop prior to filling the field but it would be handy to have a way to show the field only in a specific context (shop, group, all).

**Comment by Codencode** [comment, marked as answer]
Hi @jtraulle,
using the `prestashop.adapter.shop.context service`, you can determine if you're in a single shop context, and you can do so using the `isSingleShopContext()` method:
https://github.com/PrestaShop/PrestaShop/blob/327c9e42b556fcd676ff02376c00d8d8c3521061/src/Adapter/Shop/Context.php#L133-L140

To achieve this, you need to pass the `prestashop.adapter.shop.context` service as a parameter when defining the service related to the form type, as done here:

```yml
  # content block form
  prestashop.module.demo_multistore.form.content_block_type:
    class: 'PrestaShop\Module\DemoMultistoreForm\Form\ContentBlockType'
    parent: 'form.type.translatable.aware'
    arguments:
      - '@=service("prestashop.adapter.multistore_feature").isUsed()'
    public: true
    tags:
      - { name: form.type }
```
https://github.com/PrestaShop/example-modules/blob/fcc62e9fed408e3bad507d0fa94e01e0736198af/demomultistoreform/config/services.yml#L95-L102
