### DISCUSSION TITLE
Decorating productController in PS 8.1.6

### DISCUSSION THREAD

**Discussion by niclix** [PrestaShop/PrestaShop#36332] [Q&A]
Hi

I have an issue with decorating the productController in PS 8.1.x.
I am getting the error message
**You have requested a non-existent service "PrestaShopBundle\Controller\Admin\Sell\Catalog\Product\ProductController"**

The service yaml file is as below:
```
services:
    custom_product_controller:
        class: mymodule\Controller\Admin\CustomProductController
        decorates: PrestaShopBundle\Controller\Admin\Sell\Catalog\Product\ProductController
        arguments: ["@custom_product_controller.inner"]
```
        
Is there something I'm overlooking? I'm happy to provide more details if that would be helpful.
Thanks
