### ISSUE TITLE
[SF Migration] Entity form management - CRUD form handlers

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/PrestaShop#10285]
type: tech-issue;
status| in-progress;
comment | CRUD form handlers - WIP and 1st pages experiment;

# PR Summary

Todo:
- [x] 1st PR which introduces major concepts, interfaces and classes (https://github.com/PrestaShop/PrestaShop/pull/10974)
- [x] Handles latest code review feedbacks such as https://github.com/PrestaShop/PrestaShop/pull/10974/files#r235738277
- [x] Write documentation about CRUD controllers: explain roles involved in a CRUD page (Form Builder, Form Data Provider, Form Data Handler ...), use SQL page as an example, explain how another CRUD Symfony page can be built (for example using factories for services) https://github.com/PrestaShop/docs/pull/184
- [x] Write documentation about CQRS and Command Bus https://github.com/PrestaShop/docs/pull/184
- [x] Add unit tests for these classes

### Intro

Following the idea introduce in this PR PrestaShop/PrestaShop#8908 for Configuration forms management, maybe we can have similar workflow for Entity forms as well?

### Possible solution

Below is an example workflow of how Edit action of any Entity could look like:

![untitled diagram](https://user-images.githubusercontent.com/15143151/45053574-04158380-b093-11e8-9b87-bfc6660fdcbe.png)

What's missing:
- [Hook is not dispatched when form data is handled. Maybe some middleware between `EntityController` and `EntityFormDataHandler` could solve it?
- What would be a correct for form data validation?

 So Entity form management would require developer to implement specific `EntityFormDataHandler` & `EntityFormDataProvider` for each entity and configure `EntityFormFactory` (similar as it is wit Options).

Here is PR that defines contracts and `EntityFormFactory` implementation: https://github.com/PrestaShop/PrestaShop/pull/10286

### Possible improvement

It would be cool if we had common `EntityController` that could be used for every entity so migration could be faster, see example below.

Lets assume we are working with Product entity. First we would configure routes:

```yaml
# our implemented product listing
admin_product_listing:
  path: /product
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin/Catalog/Product/Product:listing
    _legacy_controller: AdminProduct

# no need to implement, just configure
admin_product_create:
  path: /product/new
  methods: [GET]
  defaults:
    _controller: PrestaShopBundle:Admin/Common/Entity:showCreate
   template: '@PrestaShop/Admin/Catalog/Products/create.html.twig' # we would have to render form by ourselves
   entity_form_factory: entity_form_factory_service_id

# no need to implement, just configure
admin_product_process_create:
  path: /product/new
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle:Admin/Common/Entity:processCreate
   entity_form_factory: entity_form_factory_service_id
   entity_form_data_handler: entity_form_data_handler_service_id
   redirect_after_success: admin_product_listing
   redirect_after_error: admin_product_create
```

And reusable `EntityController`:

```php
class EntityController extends FrameworkAdminBundle
{
    // EntityFormFactoryInterface could be autowired using argument resolver
    public function showCreate(EntityFormFactoryInterface $entityFormfactory, $template)
    {
        $entityCreationForm = $entityFormFactory->getForm();

        return $this->render($template, [
            'form' => $entityCreationForm->createView(),
        ]);
    }

    // services could be autowired
    public function processCreate(
        Request $request,
        EntityFormFactoryInterface $entityFormFactory,
        EntityFormDataHandlerInterface $entityFormDataHandler
    ) {
        $entityCreationForm = $entityFormFactory->getForm();
        $entityCreationForm->handleRequest($request);

        if ($entityCreationForm->isSubmitted()) {
            $errors = $entityFormDataHandler->create(
                $entityCreationForm->getData()
            );

            if (!empty($errors)) {
                $this->flashErrors($errors);

                return $this->redirectToRoute($request->attributes->get('redirect_after_error'));
            }
        }

        $this->addFlash('success', 'Successfully created!');

        return $this->redirectToRoute($request->attributes->get('redirect_after_success'));
    }

    // similar methods for editting
    // ...
}
```

This would save a lot of copy-paste code between different entity controllers as most of the actions are the same.

What's missing:
- How to persist form data when processing failed? Use session maybe?

### Note

_I did not test it and i dont know if that would actually work_
