### ISSUE TITLE
[SF Migration] Topics to explore for 1.7.6

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10602]
# Technical topics to explore for 1.7.6

- [x] Use Symfony validator service for entity form validation ✅ 
- [ ] Hooks system improvement for performances
- [x] Unit testing and integration testing: provide doc & examples (https://github.com/PrestaShop/docs/pull/333)
- [x] Define rules for domain exceptions (see https://github.com/PrestaShop/PrestaShop/issues/10674)
- [ ] Handle AdminLegacyLayoutController issue (see https://github.com/PrestaShop/PrestaShop/issues/12925)

**Comment by sarjon** [comment]
> Define rules for domain exceptions

as far as i understand, there are at least 2 types of exceptions: application and domain? if so, maybe we should define rules for both and explain the difference?

**Comment by matks** [comment]
@sarjon let's keep the discussion going in https://github.com/PrestaShop/PrestaShop/issues/10674 :)

**Comment by mickaelandrieu** [comment]
We have already discussed that with @eternoendless and you what are the 3 main topics to address in 1.7.6:

* **Put hooks on Form entity pages**: this topic is the most important one as we can't migrate theses pages if a developer can't customize them;
* **Figure out a solution for `AdminLegacyLayoutController`**: it's probably the most important one because every migrated page depends on it, so we won't be able to say we have finished the migration without removing this hard dependency;
* **Improve the form theme** as for now, the developers are forced to override the view when they add a simple form field to configuration pages. With a consistent form theme, most of the time even us won't be forced to integrate pages we are migrating. Big regression compared to the 1.6.1.x ... I guess it's your "Symfony layout" item?

It could be interesting to split this meta-issue into multiple issues so we can discuss each subject :+1:

**Comment by matks** [comment]
Form theme issue: https://github.com/PrestaShop/PrestaShop/issues/11389

**Comment by sarjon** [comment]
We have worked in Grid for a few pages already and here's what we could improve:

1. Allow defining Grid using YAML, something like:
```yaml
# grids.yml

grids:
  customers: # becomes grid id
      columns:
          id:
              type: data    # simple data column that display field
              name: { key: 'ID', domain: 'Admin.Catalog.Feature' }    # translatable name
              options:
                  field: id_customer    # field name of data
          full_name:
              type: special_full_name_column
              name: Full name # can be simple string
              options:
                  first_name_field: firstname
                  last_name_field: lastname
```
So it could be translated into actual service.

2. Introduce some kind of middlewares to allow more flexible grid modifications. For example, you could hook in your middle so it can remove row actions for records that do not match some condition. 
I image it something like this:
```yaml
grid_middleware:
  customers: 
    - 'my_custom_customers_middleware' # service id of middleware   
```
or 
```yaml
services:
  my_custom_customers_middleware:
    class: 'MiddlewareClass'
    tags: 
      - { name: grid.middleware, grid: customers }  
```
Either way, its just some quick random thoughts.
3. Improve presenter. Grid that is passed to template should be fully prepared for rendering. In additionl, instead if returning `array` use immutable `GridView` object. 
4. Improve templating, make it easier and more customizable

@matks @mickaelandrieu wdyt?
