### ISSUE TITLE
Enable connection to MySQL with SSL/TLS

### ISSUE THREAD

**Issue by Bettelstab** [PrestaShop/PrestaShop#10784]
I recently moved my database to an external server and I wanted to use TLS encryption for the database connection. If I remember correctly, I got an SSL connection error in prestashop because there were no SSL options specified. In my case, the only option I needed was MYSQL_ATTR_SSL_CA. At the end, I added it manually in /classes/db/DbPDO.php, line 81:
```
return new PDO($dsn, $user, $password, array(
            PDO::ATTR_TIMEOUT => $timeout,
            PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => true,
            PDO::MYSQL_ATTR_SSL_CA => '/var/www/html/httpdoc/ca.pem'
        ));
```

I also had to add it manually in /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php. There is an $options parameter, but I couldn't get it to work.

I suggest to make the following options configurable:
PDO::MYSQL_ATTR_SSL_KEY, PDO::MYSQL_ATTR_SSL_CERT and MYSQL_ATTR_SSL_CA.

**Comment by khouloudbelguith** [comment]
Hi @Bettelstab,

Thanks for your report.
@eternoendless, @PrestaShop/prestashop-core-developers what do you think of this issue?

Best regards, Khouloud

**Comment by PierreRambaud** [comment]
@Bettelstab For the moment you can try to change doctrine configuration in your config.yml file and add these options (do not remove the current configuration).

```yml
# Doctrine Configuration
doctrine:
  dbal:
    options:
      MYSQL_ATTR_SSL_CA : %ca_cert%
      MYSQL_ATTR_SSL_KEY : %private_key%
      MYSQL_ATTR_SSL_CERT : %public_cert%
```
