### ISSUE TITLE
[SF Migration] Be able to deprecate a Symfony route

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#12432]
Symfony provides several features to deprecate a service: aliases, 'deprecated' annotation ...

But it seems there is not the same features for routes 😁 .

So we wanted to rename a route in https://github.com/PrestaShop/PrestaShop/pull/10595#discussion_r252193093 in order to comply with our new naming conventions, but this seems to create issues.

**We need to explore the issue and solve it in order to allow us to deprecate and replace old routes with new ones.**

**Comment by matks** [comment]
Discussion in progress with Symfony team to see if we can benefit from an alias or deprecation feature for routing: https://github.com/symfony/symfony/issues/6088

But it will only be for SF 4 ...

**Comment by stof** [comment]
We have 2 entry points for the routing component: matching and url generation. We need to evaluate how each use case would happen:

- what would a deprecated route mean for URL matching ? We cannot trigger deprecations in the client sending us the HTTP request. I'm not sure what deprecating a route should mean for the matching
- for URL generation, I see 2 separate use cases:
    - renaming routes, deprecating the old name. For that, an alias feature would be much better than forcing to declare a second deprecated route for which you need to keep the whole config in sync; and it would avoid confusing the matching with 2 identical routes.
    - deprecating the URL entirely. This relates to what such a deprecated route would mean during matching, as it is the url-generation side of the deprecated endpoint case of the matching.

Which of these cases would be your use cases ?

**Comment by matks** [comment]
Hi @stof thank you for asking

**Our need is on URL generation, "renaming routes, deprecating the old name" and being able to use aliases for route names would indeed solve our need.**

We just want to update a route name but since we follow SemVer we want to make sure that this change would be retro-compatible so generating an URL using the old name would still be possible.

In routing configuration, it would mean:
```
admin_metas_listing:
  path: /metas
  alias: admin_metas_index
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\ShopParameters\Meta:index'
```
- admin_metas_index is the old name that might still be used by third-parties relying on prestashop
- admin_metas_listing is the new name, that complies with our (updated) naming convention

An extra feature would be to be able to either provide an alias for a route name (so both route names are valid and can be used for URL generation) or to provide a deprecated alias for a route name. Generating an URL by using the deprecated route name would trigger a notice in logs, helping developers to find deprecated route names and stop using them. It would consequently look like this:

```
admin_metas_listing:
  path: /metas
  deprecated_alias: admin_metas_index
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\ShopParameters\Meta:index'
```

But that would be an extra 😊 we can workaround this by informing our users about the deprecation in Changelog and Developer documentation.

EDIT: another way to configure route for deprecation:
```
admin_metas_index:
  deprecated: true
  replacement: admin_metas_listing

admin_metas_listing:
  path: /metas
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle:Admin\Configure\ShopParameters\Meta:index'
```
