### ISSUE TITLE
Separate Query/Command busses

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/PrestaShop#12445]
In PrestaShop we have 2 command busses `command_bus` and `query_bus` which both use same Tactician command bus `tactician.commandbus.default` behind the scene. 

As a result, you can dispatch `Query` with both `command_bus` and `query_bus` (same with `Command`). 

But is seems that we can confgiure multiple Tactician command busses. So when registering command/handler we could attach it to specific bus, like so:

```yaml
services:
  prestashop.adapter.customer.command_handler.save_private_note_for_customer:
    class: 'PrestaShop\PrestaShop\Adapter\Customer\CommandHandler\SavePrivateNoteForCustomerHandler'
    tags:
      - name: tactician.handler
        command: 'PrestaShop\PrestaShop\Core\Domain\Customer\Command\SavePrivateNoteForCustomerCommand'
        bus: command_bus  # command can only be dispatched through command_bus and NOT query_bus         
```

However, i can see that this feature could be considered as BC break.

@matks @eternoendless wdyt?
