### ISSUE TITLE
Make Core services context independent

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/PrestaShop#12918]
I've been thinking context data injection into services (injecting context language, employee, shop & etc into constructor), it's basically the same as injecting Request object.

Example:
```yaml
services:
  prestashop.my_service:
    class: 'PrestaShop\MyService'
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext().shop.id'
```

I think that context data should come from "outer" layers (e.g. controllers, console), that way, our Core services become context independent.
