### ISSUE TITLE
Multistore does not shop the home page content

### ISSUE THREAD

**Issue by banan44** [PrestaShop/PrestaShop#13519]
Hello,
I am configuring the MultiStore function in my prestashop 1.7.5.1 but I found a strange issue that I cannot resolve. The main website have the .eu domain. I have purchased the .it domain and parked it on my server. Then I have created a new shop group called IT, set ut the .it domain in that group and selected that all functions like order, products, themes etc must be shared from the main group. So far so good. Both domains and shops worked perfectly until I decided to change the theme in IT group. This meesed up my home page. I use a free theme called Bentriz downloaded from here: https://www.hiddentechies.com/bentriz-responsive-theme-prestashop.html

This is what i did step-by-step:
At first I wanted to create a child theme for the IT group and later changed some things. For that I used this tutorial: http://build.prestashop.com/news/Child-Themes-Feature/
I have created basic child theme. theme.yml was based on the original Bentriz theme.yml. I just added 'parent: bentriz', changed the name according to the child theme name and removed the # that was before use_parent_assets: true. 
The child theme appeared in my prestashop so I selected it for the .it domain. Checked the functionality. Everything worked well so I switched back to the original Bentriz theme.
And then I noticed something wrong. The home page of the .it domain was ok, but when I entered the main shop on .eu domain I noticed the content on the home page dissapeared. All I had was the header and the footer. No middle part. 
I selected the child theme for the main domain and then switched back to the Bentriz theme. The main content is appeared again, but it dissapeared on the Italian domain (that was on Bentriz theme as well). 
I removed the child theme. The Bentriz theme was on both shops. From now on the content is shown only on domain I selected the theme last. If the last time I changed the theme in .eu domain, the main content is in there. If the last time I changed the theme in Italian shop, the main content is there.
I went to Design -> Positions and I noticed that for the shop where there is no content I do not have displayHomeTop1, displayHomeTop2 etc. positions anymore. They are only in the shop with the content on home page. In my case, when the content was on .eu domain then I have this positions on EU shop but no on IT shop. When I change the theme on the IT domain, these positions dissappear from the EU shop and appear on the IT shop. 
It's like these positions cannot work at the same time on both shops. This is strange. Does anyone know how to solve it? I am planning to add more domains and I am affraid I will have the same issue on other shops.

**Comment by khouloudbelguith** [comment]
Hi @banan44,

I did not manage to reproduce the issue with PS1.7.5.1.
I attached a video record
https://drive.google.com/file/d/1a9JspwVX_kdara344UJ6x7WNz3DujHqJ/view
I used this child theme 
[childB.zip](https://github.com/PrestaShop/PrestaShop/files/3106939/childB.zip)
Thanks to check & feedback

**Comment by banan44** [comment]
Hello. Thank you for your fast reply. I wanted to make a video for you showing the problem but the strangest thing happened. The .it shop stopped working.

Here's the video showing the main shop with EU domain and how it works on Bentriz theme and child theme I have created. At the end of the video I have switched to the IT showed me ContextErrorExeption in Back Office and some error in Front Office. The main EU shop works with no problem, both on BO and FO. Take a look:

https://drive.google.com/file/d/1XBxof8_KbJ_2-U1LELfqDWzptu-iFi7O/view?usp=sharing

 I cannot remember which theme I am currently using for the IT domain. I went to Advanced parameters - Multistore (with the setting All shops). It gives me another error. I cannot open the MultiStore tab. I have tried on All shops, main EU shop and IT shop. Check it out:

https://drive.google.com/file/d/1D0hM7rNdbfH_187UQp-ij_kfBq4GstA8/view?usp=sharing

Also you could noticed that for the main shop I have clicked the eye button to navigate to front office but for Italian domain I have typed the address. It's because the eye button next to the IT show does not work. It always opens the main shop. I think it is something wrong with this as well. The screenshot below shows the eye button I am talking about.

https://drive.google.com/open?id=1RQ1tzYgt2WLfiI-84A7_-ZGi9zupXv8f

Also, here's the link to my child theme I have created based on the Bentriz theme.yml. I have made some visual tweaks in some tpl files and css files.

https://drive.google.com/open?id=1sR6gioPo116GzzVW8R72V_nIPlE2DYIU

**Comment by khouloudbelguith** [comment]
Hi @banan44,

Thanks for your feedback.
I tried with your child theme & also it is OK in the two shops.
https://drive.google.com/file/d/1RQPM4hIcjOTZLbsSLSZHmLSRb8hrFubx/view
Could you please try to re-upload those themes, clear cache, try also to delete the file `shop1.json`, `shop2.json`, which exist in this path /YourProjetFolder/config/themes/Yourtheme/
Thanks to check & feedback.

**Comment by banan44** [comment]
Deleteing shop1.json, shop2.json solved the Error 500. Thank you for that. I did not know about these files. Now my EU shop and IT shop works so I can show you what I mean. I have made another video. You will notice that the content of the home page shows only on the domain I changed theme the last. At the end of the theme I showed you the Positions tab, where you will notice some of the positions appear only in the domain where I selected the theme last on dissapear n the other. That's i why I do not have the content on the home page. But it is a mystery to me why this happens on the original theme on both domains, child themes on both domains, and mixed themes.

https://drive.google.com/file/d/1cju3gIYRdyJSLewMGUEBlucVWRXyPFu_/view

**Comment by khouloudbelguith** [comment]
Hi @banan44,

Thanks for your feedback.
I manage to reproduce the issue with PS1.7.5.1.
Steps to reproduce the issue:
1. Edit the "Classic" theme & add some custom hooks => I edited the /themes/classic/config/theme.yml
which I added this section
```
  hooks:
    custom_hooks:
      - name: displayHomeTop1
        title: displayHomeTop1
        description: Display Content on top of 1 home page hook
      - name: displayHomeTop2
        title: displayHomeTop2
        description: Display Content on top of 2 home page hook
      - name: displayHomeTop3
        title: displayHomeTop3
        description: Display Content on top of 3 home page hook
      - name: displayHomeBottom1
        title: displayHomeBottom1
        description: Display Content on bottom 1 of home page hook
      - name: displayHomeBottom2
        title: displayHomeBottom2
        description: Display Content on bottom 2 of home page hook
      - name: displayHomeBottom3
        title: displayHomeBottom3
        description: Display Content on bottom 3 of home page hook
```
![image](https://user-images.githubusercontent.com/16067358/56725747-5e0faa00-6745-11e9-903e-7b74ee9438cb.png)

2. I select for the shop1 this theme edited => OK
3. In the Positions page => new hooks are displayed
![image](https://user-images.githubusercontent.com/16067358/56725425-bc885880-6744-11e9-91a1-9b2a248b5344.png)
4. If I select for the shop the same theme "classic" or a child theme from the classic
5. In the Positions page => new hooks are not displayed
![image](https://user-images.githubusercontent.com/16067358/56725541-f35e6e80-6744-11e9-9f50-1a77c9fdd1d3.png)

Here's the theme classic edited
[classic.zip](https://github.com/PrestaShop/PrestaShop/files/3116212/classic.zip)
