### ISSUE TITLE
All new controllers are empty after an upgrade PS 1.6 -> 1.7

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/PrestaShop#13633]
**Describe the bug**
Started a shop on 1.6.1.8 and upgraded it to 1.7.6.0. The upgrade succeeds, but all pages running on Symfony are empty.

**To Reproduce**
* Start a shop on PS 1.6.1.8
* Upgrade it to 1.7.6.0 ([the following zip file was used](https://drive.google.com/file/d/15ziaLqzjVDw6db3bN2feWZG0DZOk9Qfj/view?usp=sharing)). Note my autoupgrade module was modified to not run the UpgradeModules step.
* When the shop is complete, go to any BO page migrated to Symfony.
* When the cache exists, the content will be empty. Dropping it will allow one page to load properly, but on the second call you should get the issue again.

**Screenshots**

* Page content when the issue occurs:

![Capture d’écran du 2019-05-02 13-02-12](https://user-images.githubusercontent.com/6768917/57075435-b95e1100-6cde-11e9-96b7-d7765ec0f5bb.png)

* Twig debug data when the page is empty:

![Screenshot_2019-05-02 Symfony Profiler(1)](https://user-images.githubusercontent.com/6768917/57075481-cc70e100-6cde-11e9-9ab8-6974da198b68.png)

* Twig debug data when the page loads properly the content:

![Screenshot_2019-05-02 Symfony Profiler](https://user-images.githubusercontent.com/6768917/57075500-d7c40c80-6cde-11e9-8f49-92429e2fec37.png)

**Additionnal information**
* PrestaShop version: 1.6.1.8, upgraded to 1.7.6.0
* PHP version: 
```
PHP 5.6.40 (cli) (built: Jan 23 2019 00:10:05) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

* Used docker-compose.yml file:

```yml
version: '2'

volumes:
    db-data:

services:
    mysql:
        image: mysql:5.6
        ports:
            - "3306"
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: prestashop
    apache:
        image: prestashop/prestashop:1.6.1.8
        environment:
            PS_INSTALL_AUTO: 1
            DB_PASSWD: password
            DB_NAME: prestashop
            DB_SERVER: mysql
            PS_DOMAIN: ip6-localhost:8001
            PS_FOLDER_INSTALL: install-dev
            PS_FOLDER_ADMIN: admin-dev
            PS_DEV_MODE: 0
            PS_DEMO_MODE: 0
            PS_COUNTRY: fr
            PS_LANGUAGE: en
        ports:
            - "8001:80"
```

### Back Office credentials

demo@prestashop.com / prestashop_demo
