### ISSUE TITLE
Display an error message instead of an exception when there is an error

### ISSUE THREAD

**Issue by glo-www** [PrestaShop/PrestaShop#13783]
**Describe the bug**
After uploading the theme, when I try to activate it, I get the following 500 error:  _Cannot install module ps_newproducts. The module is invalid and cannot be loaded._
The module is not installed and not available in module catalogue, but that should not prevent theme from being installed.

**To Reproduce**
1. Import a theme which want to position "ps_newproducts" in a hook
in theme.yml:
```
displayHome:
        - ps_imageslider
        - ps_featuredproducts
        - ps_newproducts
```
2. Click "Use this theme" to activate it

**Screenshots**
![Cannot install module ps_newproducts  The module is invalid and cannot be loaded   500 Internal Server Error ](https://user-images.githubusercontent.com/406119/57692590-6de52480-7647-11e9-9a1e-3bcba466e5bd.png)

**Additionnal information**
PrestaShop version: 1.7.6.0_beta
PHP version: 5.6.35 - 7.2.4

**Comment by khouloudbelguith** [comment]
Hi @glo-www,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.beta1
I tried to install "minimal" theme v3.0.4 => I tried to use it
I have an exception
![image](https://user-images.githubusercontent.com/16067358/57694431-92d79880-7643-11e9-96a0-cd5786c6e7a6.png)

In the PS1.7.5.2, I have a red alert
![image](https://user-images.githubusercontent.com/16067358/57694461-a551d200-7643-11e9-81f3-becd696853cb.png)


Similar issue with PS1.7.6.0beta1, when I try to upload an invalid theme an exception is displayed
![image](https://user-images.githubusercontent.com/16067358/57694512-cc100880-7643-11e9-97a8-52a910b33475.png)

In the PS1.7.5.2, I have a red alert
![image](https://user-images.githubusercontent.com/16067358/57694548-e813aa00-7643-11e9-8284-74d3f2be1e47.png)

I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by PierreRambaud** [comment]
If I upload a wrong zip file
![image](https://user-images.githubusercontent.com/1462701/57785705-89792980-7732-11e9-93ee-26c06f6f8d9c.png)

**Comment by eternoendless** [comment]
I think we should display an error message instead of an exception

**Comment by colinegin** [comment]
Is this related to #13914  ?

**Comment by glo-www** [comment]
@marionf  Why is it closed?

**Comment by marionf** [comment]
@glo-www because this issue is fixed by https://github.com/PrestaShop/PrestaShop/pull/14021

**Comment by glo-www** [comment]
@marionf The subject of this issue has been changed, but the original point was that theme should be installed anayway if theme.yml tries to hook a basic Prestashop module which, for some reason, is not available (ps_newproduct for exemple).

**Comment by matks** [comment]
> @marionf The subject of this issue has been changed, but the original point was that theme should be installed anayway if theme.yml tries to hook a basic Prestashop module which, for some reason, is not available (ps_newproduct for exemple).

But the the theme would be buggy then 🤔 ?

It's like dependencies: if A requires B, it's useless to install A without B as it will be dysfunctional anyway

**Comment by glo-www** [comment]
> 
> 
> > @marionf The subject of this issue has been changed, but the original point was that theme should be installed anayway if theme.yml tries to hook a basic Prestashop module which, for some reason, is not available (ps_newproduct for exemple).
> 
> But the the theme would be buggy then 🤔 ?
> 
> It's like dependencies: if A requires B, it's useless to install A without B as it will be dysfunctional anyway

In this case B is not mandatory, just a basic feature that should be installed in Prestashop by default. Theme works without it.

**Comment by matks** [comment]
> > > @marionf The subject of this issue has been changed, but the original point was that theme should be installed anayway if theme.yml tries to hook a basic Prestashop module which, for some reason, is not available (ps_newproduct for exemple).
> > 
> > 
> > But the the theme would be buggy then 🤔 ?
> > It's like dependencies: if A requires B, it's useless to install A without B as it will be dysfunctional anyway
> 
> In this case B is not mandatory, just a basic feature that should be installed in Prestashop by default. Theme works without it.

Yes, but we have no way to know that, right ?
For example Theme Classic requires the following modules:
```
modules_to_hook:
      displayNav1:
        - ps_contactinfo
      displayNav2:
        - ps_languageselector
        - ps_currencyselector
        - ps_customersignin
        - ps_shoppingcart
      displayTop:
        - ps_mainmenu
        - ps_searchbar
      displayHome:
        - ps_imageslider
        - ps_featuredproducts
        - ps_banner
        - ps_customtext
      displayFooterBefore:
        - ps_emailsubscription
        - ps_socialfollow
      displayFooter:
        - ps_linklist
        - ps_customeraccountlinks
        - ps_contactinfo
      displayLeftColumn:
        - ps_categorytree
        - ps_facetedsearch
      displaySearch:
        - ps_searchbar
      displayProductAdditionalInfo:
        - ps_sharebuttons
      displayReassurance:
        - blockreassurance
      displayOrderConfirmation2:
        - ps_featuredproducts
      displayCrossSellingShoppingCart:
        - ps_featuredproducts
```

How can we know which are ones are mandatory and which ones are not ?
