### ISSUE TITLE
Inline flag in theme.yml does not work

### ISSUE THREAD

**Issue by dennispw** [PrestaShop/PrestaShop#13872]
**Describe the bug**

Original forge ticket: http://forge.prestashop.com/browse/BOOM-5606

When declaring a custom asset such as a `.css` or `.js` file we have the option of using the `inline: true` flag. In theory this should inject the contents of the file into a `style` or `script` tag accordingly.

While a `style` and `script` tag is created successfully, the contents of the file is missing:

```
<style>
  /* ---- styles @ /mystore/themes/sometheme/assets/css/styles.css ---- */
</style>
```

When enabling the debug mode you get the following error:

```
Warning: file_get_contents(/mystore/themes/sometheme/assets/css/styles.css): failed to open stream: No such file or directory
```

The file exists. The file is not empty. The file is formatted correctly.

If it was working correctly this would be an *incredible* option/feature to have at our disposal.

**To Reproduce**
See ticket link above.

**Screenshots**
See ticket link above.

**Additional information**
PrestaShop version: 1.7.3.2 -> 1.7.6.0 beta (at least)

**Comment by khouloudbelguith** [comment]
Hi @dennispw,

Thanks for your report.
I manage to reproduce the issue with PS1.7.6.0beta1 & PS1.7.5.2 (debug mode enabled)
I used this theme
[khouloud.zip](https://github.com/PrestaShop/PrestaShop/files/3197623/khouloud.zip)
In the FO => Product page => I have this error
![image](https://user-images.githubusercontent.com/16067358/58018675-5ac8cd80-7afb-11e9-91f9-81b88bd1592c.png)
If I replace this

```
  js:
      product:
        - id: cat-extra-lib
          path: assets/js/custom.js
          inline: true

```
By this

```
  js:
      product:
        - id: cat-extra-lib
          path: assets/js/custom.js
          inline: false

```
The exception doesn't exist anymore
I’ll add this to the debug roadmap so that it’s fixed. If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!
