### ISSUE TITLE
Refacto the CategoryFilters building process

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#14113]
**Is your feature request related to a problem? Please describe.**
This refacto is linked to this bugfix PR https://github.com/PrestaShop/PrestaShop/pull/13984
We had to introduce a request stack injection inside a service to allow getting back the request attribute, which is not satisfying at all
Considering the time left before release, the solution has been temporarily accepted but we should propose a better solution

**Describe the solution you'd like**
I was thinking of dropping the event listener solution in favor of using the already existing `prestashop.core.search.builder` service:

```yaml
    prestashop.core.search.builder:
        class: 'PrestaShop\PrestaShop\Core\Search\Builder\ChainedFiltersBuilder'
        arguments:
          -
            - '@prestashop.core.search.builder.class'
            - '@prestashop.core.search.builder.repository'
            - '@prestashop.core.search.builder.request'
            - '@prestashop.core.search.builder.event'
            - '@prestashop.core.search.builder.persist'
```

When you consider at the `prestashop.core.search.builder.request` it already has the necessary information to modify correctly the `Filter`
So the idea would be to create other services implementing `FiltersBuilderInterface` but which would be adapted to specific use cases. Then we could have something like this:

```yaml
    prestashop.core.search.builder:
        class: 'PrestaShop\PrestaShop\Core\Search\Builder\ChainedFiltersBuilder'
        arguments:
          -
            - '@prestashop.core.search.builder.class'
            - '@prestashop.core.search.builder.repository'
            - '@prestashop.core.search.builder.request'
            - '@prestashop.core.search.builder.category'
            - '@prestashop.core.search.builder.event'
            - '@prestashop.core.search.builder.persist'
```

**Describe alternatives you've considered**

If we try to go a bit further, instead of modifying the service definition each time we need to add a new builder we could use a tag system so that `prestashop.core.search.builder` can fetch all the necessary builders easily. This also has the advantage to allow modules to inject their own builder either to modify the existing `Filters` or to add their own?.

```yaml
    prestashop.core.search.builder:
        class: 'PrestaShop\PrestaShop\Core\Search\Builder\ChainedFiltersBuilder'
        arguments:
          -
            - '@prestashop.core.search.builder.class'
            - '@prestashop.core.search.builder.repository'
            - '@prestashop.core.search.builder.request'
            - '@prestashop.core.search.builder.event'
            - '@prestashop.core.search.builder.persist'

    prestashop.core.search.builder.request:
        class: 'PrestaShop\PrestaShop\Core\Search\Builder\CategoryFiltersBuilder'
        arguments:
            - '@prestashop.adapter.legacy.configuration'
            - '@prestashop.adapter.shop.context'
            - '@prestashop.adapter.feature.multistore'
            - '@prestashop.adapter.shop.context'
            - '@=service("prestashop.adapter.legacy.context").getContext().shop.id_category'
        tags:
            - { name: prestashop.filters_builder }
               
```
