### ISSUE TITLE
HTTP 500 Error on Installation Assistant

### ISSUE THREAD

**Issue by kwaun** [PrestaShop/PrestaShop#16142]
**Describe the bug**
I got this error while installing PS 1.7.6.1 in a prestashop/prestashop:1.7 docker container.

**To Reproduce**
1. Install PS container
docker-compose.yml
```
version: '2'
 
services:
    db:
        image: mysql:5
        command:
            --default-authentication-plugin=mysql_native_password
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: prestashop
            MYSQL_USER: prestashop
            MYSQL_PASSWORD: prestashop
        restart: always
        networks:
          - default
    app:
        image: prestashop/prestashop:1.7
        environment:
            PS_INSTALL_AUTO: 0
            DB_PASSWD: prestashop
            DB_NAME: prestashop
            DB_SERVER: db
        networks:
          - proxy
          - default
        volumes:
          - html:/var/www/html/
        labels:
          - traefik.enable=true
          - traefik.docker.network=proxy
          - ...

volumes:
  db-data:
  html:

networks:
  proxy:
    external: true
```
```
docker-compose up -d
```
2. Open http://MYDOMAIN/
3. Follow the installation steps.
4. The last step fails and shows this information.
```
Store installation
12%
Create database tables

An error occurred during installation...
You can use the links on the left column to go back to the previous steps, or restart the installation process by clicking here.

1: HTTP 500 - error -
```
The PS log shows theese lines:
```
[...]
172.19.0.2 - - [27/Oct/2019:14:54:26 +0000] "GET /install/index.php?generateSettingsFile=true&_=1572188066897 HTTP/1.1" 200 314 "http://MYDOMAIN/install/index.php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
zend_mm_heap corrupted
[Sun Oct 27 14:54:37.472674 2019] [:error] [pid 24] [client 172.19.0.2:39508] PHP Warning:  require_once(/var/www/html/var/cache/prod/namespaced_class_stub.php): failed to open stream: Permission denied in /var/www/html/classes/PrestaShopAutoload.php on line 160, referer: http://MYDOMAIN/install/index.php
[Sun Oct 27 14:54:37.472729 2019] [:error] [pid 24] [client 172.19.0.2:39508] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/var/cache/prod/namespaced_class_stub.php' (include_path='/var/www/html/vendor/pear/pear_exception:/var/www/html/vendor/pear/console_getopt:/var/www/html/vendor/pear/pear-core-minimal/src:/var/www/html/vendor/pear/archive_tar:.:/usr/local/lib/php') in /var/www/html/classes/PrestaShopAutoload.php on line 160, referer: http://MYDOMAIN/install/index.php
```

Notice the "zend_mm_heap corrupted" line.

Inside the container after the error:
```
# ls -l /var/www/html/var/cache/prod/namespaced_class_stub.php
---------- 1 www-data www-data  12830 Oct 27 15:54 namespaced_class_stub.php
```

Before starting the instalation procedure that file permissions were correct!:
```
# ls -l /var/www/html/var/cache/prod/namespaced_class_stub.php
-rw-r--r-- 1 www-data www-data  12830 Oct 27 15:54 namespaced_class_stub.php
```

Have to say that I tried the container image prestashop/prestashop-git:7 and it worked flawlessly.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 5.6.40
Docker CE version: 19.03.4
Host OS: Debian GNU/Linux 10.1

PS: This is my first bug report in history. Sorry if I did it wrong.

**Comment by khouloudbelguith** [comment]
Hi @kwaun,

Thanks for your report.
After running `docker-compose up`
I have errors: `prestashop exited with code 1`
It is an issue reported previously in this ticket: https://github.com/PrestaShop/PrestaShop/issues/15941 and fixed by this PR: https://github.com/PrestaShop/PrestaShop/pull/15942

Thanks to check  & feedback.

**Comment by khouloudbelguith** [comment]
@kwaun,

I used this script

```
version: '2'

volumes:
    db-data:
    vendor:
    var:

services:
    mysql:
        image: mysql:5
        ports:
            - "3309"
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: prestashop
        restart: always
    apache:
        container_name: prestashop
        image: prestashop/prestashop:1.7
        environment:
            PS_INSTALL_AUTO: 1
            DB_PASSWD: password
            DB_NAME: prestashop
            DB_SERVER: mysql
            PS_DOMAIN: localhost:8001
            PS_FOLDER_INSTALL: install-dev
            PS_FOLDER_ADMIN: admin-dev
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www/html/:delegated
            - vendor:/var/www/html/vendor
            - var:/var/www/html/var
        restart: always

```

After running `docker-compose up`, The PrestaShop is well installed & not need to install it again.
Thanks!
