### ISSUE TITLE
docker-compose up | Can't launch docker-compose on Windows

### ISSUE THREAD

**Issue by Dayniight** [PrestaShop/PrestaShop#17479]
Hi, 

When i try to start a "docker-compose up"  i cant finish the launch of it.

I tried to do delete my rep and re-clone and i tried to re-start another docker-compose up

![image](https://user-images.githubusercontent.com/27630157/73461524-94382500-437a-11ea-82d5-970744e4c494.png)

OS : Windows 10 version 1903
Docker : 2.1.0.5

**Comment by khouloudbelguith** [comment]
Hi,

With PS1.7.7x, I have this error
![docker_177x](https://user-images.githubusercontent.com/16067358/73663099-39197180-469d-11ea-90e6-bd0c9b673cb9.PNG)
With PS1.7.6.x, I have this error
![docker_176x](https://user-images.githubusercontent.com/16067358/73663118-420a4300-469d-11ea-8217-b94156629f09.PNG)

Thanks!

**Comment by rauleburro** [comment]
I managed to get it working by running docker with wsl2 enabled

**Comment by theodiablo** [comment]
@Dayniight did you find  a way to overcome this in the end? How did you do?

Thanks :-)

**Comment by Toumash** [comment]
This docker-compose certainly is working

```yml
version: '2'

services: 
  prestashop:
    image: prestashop/prestashop:1.7-7.2-apache
    ports:
      - 80:80
    links:
      - mariadb:mariadb
    depends_on:
      - mariadb
    # volumes:
      # - ./docker/common:/scripts
      # - ./src:/var/www/html
      # - ./src/modules:/var/www/html/modules
      # - ./src/themes:/var/www/html/themes
      # - ./src/override:/var/www/html/override
    environment:
      - PS_DEV_MODE=1
      - DB_SERVER=mariadb
      - DB_USER=root
      - DB_PASSWD=root
      - DB_NAME=prestashop
      - PS_INSTALL_AUTO=1
      - PS_DOMAIN=localhost
      - PS_FOLDER_ADMIN=admin123
      - ADMIN_MAIL=demo@gmail.com
      - ADMIN_PASSWD=admin

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prestashop

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb
    ports: 
      - 81:80 
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root
 
```
