### ISSUE TITLE
Lack of AdminCustomersControllerCore

### ISSUE THREAD

**Issue by samberrry** [PrestaShop/PrestaShop#17787]
In my module I've overridden the AdminCustomersControllerCore class which was responsible for customer manipulation. Now (I don know in which ps update) this class is removed... and my module does work. I figured out that the class which is responsible now is the CustomerController in PrestaShopBundle.
Why is it changed? 
And how can I implement my logic... Is there any way to override this class?

**Comment by matks** [comment]
@vhessam AdminCustomersControllerCore was removed from PrestaShop in v1.7.6 because the Customers page was migrated to Symfony, as you found out.

As we migrate slowly Back-Office pages to Symfony, we rewrite the controllers, the templates and the Javascript of these pages and delete the old files as they are now disabled.

You can override Symfony Controllers behavior by using routing override: instead of modifying the php file, you modify the Symfony routing to redirect incoming requests to *your* controller.
This means
- create a new Controller of your own (https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/)
- define a routing that overrides existing routing

Example of such routing
```
// core routing
admin_payment_preferences:
    path: /preferences
    methods: [GET]
    defaults:
        _controller: PrestaShopBundle:Admin\Improve\Payment\PaymentPreferences:index
        _legacy_controller: AdminPaymentPreferences
        _legacy_link: AdminPaymentPreferences
```
⬇️ 
```
admin_payment_preferences:
    path: /preferences
    methods: [GET]
    defaults:
        _controller: MyModule\Controller:index // here it is !
        _legacy_controller: AdminPaymentPreferences
        _legacy_link: AdminPaymentPreferences
```
