### ISSUE TITLE
Docs do not mention since which version modules can use modern routing

### ISSUE THREAD

**Issue by michaelKaefer** [PrestaShop/PrestaShop#18240]
Docs do not mention since which PrestaShop version modules can use modern routing like this:

```
# modules/your-module/config/routes.yml
your_route_name:
    path: your-module/demo
    methods: [GET]
    defaults:
      _controller: 'MyModule\Controller\DemoController::demoAction'
```
