### ISSUE TITLE
Register hooks as symfony services

### ISSUE THREAD

**Issue by zulus** [PrestaShop/PrestaShop#18991]
#### Is your feature request related to a problem?

I would like to use all symfony features on hook level. Especially twig rendering, or form handler processing.

#### Describe the solution you'd like

Use symfony tags to register hook executors

```yaml
my_service:
    tags:
        - { name: prestashop.hook, hook: actionAfterCreateCategoryFormHandler, method: handlerMethod }
```

In this way explicit "registerHook" could be avoided I hope 

#### Alternatives you've considered

Hooks could be replaced by event dispatcher/event subscribers, similar to doctrine listeners
