### ISSUE TITLE
Back office will not recognise new theme

### ISSUE THREAD

**Issue by musaffar-patel** [PrestaShop/PrestaShop#20058]
Hi

These are the steps I have undertake:

- duplicated the classic theme into a new theme folder "themes/custom"
- Modified themes/custom/config/theme.yml changing the meta information as shown below:

```
name: custom
display_name: Custom
version: 1.0.0
author:
  name: "Musaffar Patel"
  email: "pub@prestashop.com"
  url: "http://www.prestashop.com"

meta:
  compatibility:
      from: 1.7.0.0
      to: ~
```

- Cleared Prestashop cache through back office and by emptying /var/cache/ folders.
- Navigate to Design > Theme & Logo

However, I see two themes, but both are presented as the "Classic Theme" instead of the one theme being the custom theme.  This prevents me from using the custom theme.

See attachment.
![screenshot](https://user-images.githubusercontent.com/44204668/86511682-550f7380-bdf3-11ea-99e7-d430b8676342.jpg)

Kind Regards
Musaffar
