### ISSUE TITLE
Cannot override assets configuration in child theme

### ISSUE THREAD

**Issue by Seb33300** [PrestaShop/PrestaShop#20420]
I have a theme using this `assets` configuration in the `theme.yml` file:
``` yaml
assets:
  css:
    all:
      - id: font-awesome
        path: assets/css/font-awesome/css/font-awesome.css
        media: all
        priority: 200
```

In my child theme, I want to override the `font-awesome` asset config to use a more recent version (upgrade to Font Awesome v5 while the theme still use v4).
I set the `theme.yml` file of my child theme with this config:
``` yaml

assets:
  use_parent_assets: true
  css:
    all:
      - id: font-awesome
        path: assets/css/font-awesome/css/all.css
        media: all
        priority: 200
```

The result is that the old `font-awesome.css` is still loaded instead of the new `all.css` set in my child theme.

Am i doing something wrong or is it a bug?
