### ISSUE TITLE
Advanced issue management: use Template configuration file

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#21694]
Today, when a GitHub user opens the link https://github.com/PrestaShop/PrestaShop/issues/new/choose he has 4 choices:

- choose a "bug report" issue template
- choose a "feature request" issue template
- choose a "I need help" issue template
- view our security policy

However there is no real "I need help" issue template. This is rather a message to provide relevant informations for people looking for help: we use the template as a way to carry our informations. But regularly we have people just type their questions into the title or remove the body of the issue and put there their question anyway 😅 . Basically they are mistaken by the fact that this is an issue template. This way of carrying the information is not efficient.

According to https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser we could create a configuration file and use `contact_links` to _redirect_ users looking for help to some page (maybe on devdocs) where the relevant informations would be provided _and it cannot be submitted as a GitHub issue._

So the config.yml would look like this:
```
blank_issues_enabled: true
contact_links:
  - name: I need help
    url: http://devdocs.prestashop.com/i-need-help
    about: Please ask and answer questions here.
```

Wdyt @SimonGrn @PrestaShop/prestashop-maintainers ?
