### ISSUE TITLE
In multi-store setting, editing a customer, it is possible to choose invalid groups.

### ISSUE THREAD

**Issue by lmeyer1** [PrestaShop/PrestaShop#23192]
#### Describe the bug

In multi-store setting, editing a customer, it is possible to choose invalid groups.
Given a customer that belongs to store A and a group that exists only in store B,
when in *All shops* contexts, I click on *Customer settings*, select a customer and click *Edit*
then the list of groups in *Group Access* and *Default Customer Group* list all groups of all stores.
I can select any group in both *Group Access* and *Default Customer Group* and save them.
If I select a default customer group for the customer that does not exist in the store the customer belongs to, it will be saved like this without further check.

#### Expected behavior

I expect that a customer in shop A can only be member of a group associated with shop A, and that customer's default group can only be a group associated with shop A.

Both lists in  *Group Access* and *Default Customer Group* should only display groups that exist in the shop the customer belongs to.

#### Steps to Reproduce

Setup:
- Create a multi-store environment with at least two stores that do not share customers.
- Create a customer in store A
- Create a customer group that is not associated with store A

1. Select *All shops* context
2. Go to *Customers list*
3. Select a row (customer of shop A created above), click *Edit*
4. The group created above (that does not belong to shop A) shows up in both *Group Access* and *Default Customer Group*
5. You can select the invalid group and save it.

#### Additional information

* PrestaShop version: 1.6.1.1 and 1.7.7.1
* PHP version: N/A

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Thanks for your issue!
I reproduced it with develop, PS1.7.7.1 and PS1.7.4.1, see the attached screen record below:

https://drive.google.com/file/d/1ECpd_GQOcz311xKR73hy0fCYIDTnL0iC/view

I’ll add this to the debug backlog so that it’s fixed.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!

Thank you

**Comment by lmeyer1** [comment]
Thank you for your answer. Yes, I might fix it, but there is a problem in fixing it.

If the customer belongs to only on shop, there is no problem, we can simply look up the groups of the shop the customer belongs to.

Things become more intricate, if the customer belongs to a shop in a shop group with sharing of customers enabled. In this case, the customer groups must also be shared in the shop group, otherwise it is possible to choose a customer group that is only valid in one of the shops of the shop group.

For this case we could admit two solutions:
1. The necessary conditions for this customer to always have a valid configuration are:
    - *Default Customer Group* must be a customer group that is associated to all shops sharing the customer. We only list groups associated to all shops that share that customer.
    - In *Group Access* the chosen default customer group must be checked. (Prestashop already takes care of this). In *Group Access* we list all groups associated to the shop the customer belongs to.
2. This would be a minor problem, and the shop administrator should take care that the association shop - shop group is consistent if there are shops that share customers. We would not implement a technical solution for this case.

I would tend to opt for the second solution, and implement a simple solution:
Both *Group Access* and *Default Customer Group* list the groups associated to the shop the customer belongs to.

What is your opinion ?

**Comment by lmeyer1** [comment]
I'm sorry, I'm not able to fix this in PS 1.7.

Unfortunately the backtrace goes through an autogenerated file `var/cache/prod/ContainerLcgk3rx/getPrestashop_Bundle_Form_Admin_Sell_Customer_CustomerService.php` where `$id_shop` should be passed to `$this->services['prestashop.adapter.form.choice_provider.group_by_id_choice_provider']->getChoices()`.

I have no idea how Symfony DI works, and even less how to change arguments in the injected dependencies. Can you provide a link to doc about this ? I didn't find it in https://devdocs.prestashop.com/1.7.

Thank you.

**Comment by hibatallahAouadni** [comment]
@matks could you please help @lmeyer1 
Thanks in advance :pray:

**Comment by matks** [comment]
Sorry for late answer, the documentation is https://devdocs.prestashop.com/1.7/modules/concepts/services/

**Comment by hibatallahAouadni** [comment]
Thanks @matks

**Comment by lmeyer1** [comment]
Thanks, I will try to understand it. This DI and indirection is really very very tough! In PS, there was one class for each entity and for each controller, a simple architecture. Now in PS 1.7, there are hosts of classe in addition: an adapter, a wrapper, two providers, ten interfaces and three factories. Difficult to see the big picture.

Just a simple question : what is the immense benefit from that structure that outweighs such a immense complexification ?

**Comment by lmeyer1** [comment]
I try to find out how to restrict the choices for the customer group, but I don't find a solution.

In `src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml` I could change `getChoices()` to `getChoicesByShopId()` :
```
prestashop.bundle.form.admin.sell.customer.customer:
    class: 'PrestaShopBundle\Form\Admin\Sell\Customer\CustomerType'
    arguments:
        - '@=service("prestashop.adapter.form.choice_provider.gender_by_id_choice_provider").getChoices()'
        - '@=service("prestashop.adapter.form.choice_provider.group_by_id_choice_provider").getChoicesByShopId()'
        - '@=service("prestashop.adapter.form.choice_provider.risk_by_id_choice_provider").getChoices()'
        - '@=service("prestashop.core.b2b.b2b_feature").isActive()'
        - '@=service("prestashop.adapter.legacy.configuration").get("PS_CUSTOMER_OPTIN")'
    calls:
        - { method: setTranslator, arguments: ['@translator'] }
    tags:
       - { name: form.type }
 ```
and create that new method in `src/Adapter/Form/ChoiceProvider/GroupByIdChoiceProvider.php`  similar to `getChoices`
```
    public function getChoicesByShopId()
    {
        $choices = [];
+       $context = Shop::getContext();  // get current context, switch context to customer's shop, and switch back after query
+       switch ($context)
+           case Shop::CONTEXT_SHOP:
+               $id = Shop::getContextShopId();
+               break;
+           case Shop::CONTEXT_GROUP:
+               $id = Shop::getContextShopGroupId();
+               break;
+           default:
+           $id = null;
+       }
+       Shop::setContext(Shop::CONTEXT_SHOP, $customer_id_shop)   // <= how can I get here the id_shop the customer belongs to ?
        $groups = Group::getGroups($this->contextLangId, true);
+       Shop::setContext($context, $id);

        $groupsToSkip = [
```
The problem I face with this approach is that I dont know how to get access to the id of the shop the customer belongs to.

Is this a valid starting point? If yes how to solve the problem ?
If no, maybe I don't understand DI yet ?
