### ISSUE TITLE
Symfony does not recognize module classes from front/services.yml

### ISSUE THREAD

**Issue by Delota** [PrestaShop/PrestaShop#23280]
#### Describe the bug

I'm creating a module with the new Symfony style.
I defined the configs as follows:
```
config/front/services.yml
config/admin/services.yml
config/services.yml
```

All contain the same content, however, when loading anything in the front I get:
```
Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Invalid service "MyModule\MyClass": class "MyModule\MyClass" does not exist.
```

services.yml
```
services:
  _defaults:
    public: true

  MyModule\MyClass:
    class: MyModule\MyClass

  'mymodule.scoped_http_client':
    class: 'http_client'
    factory: ['@MyModule\MyClass', 'create']
    arguments:
      $baseUri: 'https://someuri/'
```

Everything works correctly in the admin and the services are registered succesfully there.
When I delete `config/front/services.yml`, everything works normally.

It seems like my autoload is not loaded correctly or something for the front-end of the system.
I already ran `dump-autoload`  and cleared caches etc.

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @Delota 

Please check our [documentation](https://devdocs.prestashop.com/1.7/modules/creation/module-file-structure/), and check if your create the proper module tree.
Don't forget to feedback.

Thanks!

**Comment by matks** [comment]
@Delota I think (not 100% sure) that `config/front/services.yml` is usable when you create a new web page powered by Symfony and served by your module. But I am not sure (again, needs to be verified) that you can use the services defined there on a regular FO page.

Because regular FO pages are powered by PrestaShop legacy framework and Smarty.

**Comment by hibatallahAouadni** [comment]
Hello @Delota ,

Since we had no news from you for more than 20 days, I'll close this ticket to avoid cluttering up the backlog.
Please note that you can always create a new one if further information pops up.

Thanks!

**Comment by devantoine** [comment]
Even though the issue is closed for 2 years, I'll post here for people like me bumping on this page after having the exact same issue:

You've got the

> "Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Invalid service "MyModule\MyClass": class "MyModule\MyClass" does not exist." 

error when you're defining a front service which takes arguments.

At first I thought it was because I was injecting some services not defined in the front container but then I tried passing string as arguments and I had the same error.

I thought it was really weird because PrestaShop defines services with arguments for the front container, **but** these arguments are not named ones.

So instead of having

```
  'mymodule.scoped_http_client':
    class: 'http_client'
    factory: ['@MyModule\MyClass', 'create']
    arguments:
      $baseUri: 'https://someuri/'
```

You should have

```
  'mymodule.scoped_http_client':
    class: 'http_client'
    factory: ['@MyModule\MyClass', 'create']
    arguments:
      - 'https://someuri/'
```

I don't understand this limitation because right now, the Symfony version being used is the 4.4 which allows the usage of named arguments 🤷
