### ISSUE TITLE
1.7.8.x additional hook in product form data handler

### ISSUE THREAD

**Issue by zuk3975** [PrestaShop/PrestaShop#24250]
#### Is your feature request related to a problem?
It is already possible to extend the behavior by registering own custom CommandsBuilder in module, but it might be an overhead  in many cases, so following solution should allow to achieve the same without forcing to have this additional class.

#### Describe the solution you'd like

Additional hook in ProductFormDataHandler (https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Form/IdentifiableObject/DataHandler/ProductFormDataHandler.php#L88) something like this:

    public function update($id, array $data)
    {
        $commands = $this->commandsBuilder->buildCommands(new ProductId($id), $data);

        // new hook goes here with $id, $data and $commands as params

        foreach ($commands as $command) {
            $this->bus->handle($command);
        }
    }

Using this hook developer could modify commands order, add/ remove commands before they are dispatched and is not forced to use its own commandBuilder.

ping @jolelievre we've briefly discussed this idea

**Comment by hibatallahAouadni** [comment]
Hello @zuk3975 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
If you are willing to implement this feature into PrestaShop as a [Pull Request](https://devdocs.prestashop.com/1.7/contribute/contribute-pull-requests/), the teams will be happy to help you by ensuring that it is appropriate and coherent with the rest of the project. If that is the case, please let us know :wink: 

Thank you

**Comment by Hlavtox** [comment]
Ping @tleon @jolelievre @nicosomb Guys, close this please. I think it's not relevant anymore.

**Comment by boo-code** [comment]
Agreeing with @Hlavtox that this can be closed, with the reason rather than just the conclusion: the overhead this issue was working around no longer exists.

In 2021 extending the product form meant supplying your own `CommandsBuilder`, which is why a hook looked like the cheaper option. Today `ProductCommandsBuilder` is a tagged collection:

```yaml
PrestaShop\...\CommandBuilder\Product\ProductCommandsBuilder:
  arguments:
    - !tagged core.product_command_builder

PrestaShop\...\CommandBuilder\Product\UpdateProductCommandsBuilder:
  tags:
    - { name: 'core.product_command_builder', priority: 10 }
```

A module contributes by declaring one service with that tag in its own `config/services.yml` - the same file `ps_facetedsearch` already ships - and it takes part in the same ordering as core's own builders through `priority`. No replacement of anything, no additional class beyond the builder itself.

That is also a better shape than the hook this issue proposed, and the difference is not cosmetic. Handing `$commands` to listeners so they can "modify commands order, add/remove commands" makes every module's behaviour depend on the array another module happened to produce, and on hook execution order, which is a position rather than a declared relationship. The tag expresses the same intent with the dependency written down - and core already relies on that ordering being explicit:

```yaml
# VERY IMPORTANT this builder must be the last one, it will avoid conflicts with previous commands
# that may not be compatible with the updated type, its priority musk be kept lower than others
TypeCommandsBuilder:
  tags:
    - { name: 'core.product_command_builder', priority: -42 }
```

A hook firing after `buildCommands()` would sit outside that ordering entirely and could undo it.

So the capability asked for is available, through a mechanism that arrived after the issue was filed, and the alternative would weaken a constraint core depends on. Nothing left to build here.
