### ISSUE TITLE
Connot install prestashop with docker compose

### ISSUE THREAD

**Issue by Julien-ADDREA** [PrestaShop/PrestaShop#24524]
#### Describe the bug

I have tried several times to install prestashop with docker but the same error occurs every time

```
An error occurred during installation...
You can use the links on the left column to go back to the previous steps, or restart the installation process by clicking here.

1: Cannot download language pack "fr"
```

#### Expected behavior

Clean install normally ?!

#### Steps to Reproduce

```
version: "3.9"
services:

    # MYSQL
    mysql:
        container_name: mysql.dev
        image: mysql:5
        restart: always
        ports:
            - "3305:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secure
            MYSQL_DATABASE: prestashop
        volumes:
            - ./.docker/mysql/data:/var/lib/mysql
        networks:
            - dev-network

    # PRESTASHOP
    prestashop:
        container_name: prestashop.dev
        image: prestashop/prestashop
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
        networks:
            - dev-network

networks:
    dev-network:
        driver: bridge
```

**Screenshots**

![image](https://user-images.githubusercontent.com/59737586/118485393-adecaf80-b718-11eb-9317-2c3c047de110.png)

#### Additional information

* PrestaShop version: latest (1.7)
* PHP version: Use Prestashop docker php image v7
