### ISSUE TITLE
Report a bug with child theme into theme.yml

### ISSUE THREAD

**Issue by Maofree** [PrestaShop/PrestaShop#24672]
#### Describe the bug
I report a problem with the child theme. It is not possible to add extra files into theme.yml with the line
`use_parent_assets: true`
or
`use_parent_assets: false`
I get a php error. If I remove this line
`use_parent_assets: true`
all seems ok and my extra file present into the child theme is loaded and the rest prestashop assets

#### Expected behavior
the goal should be load the parent assets more my extra file

#### Steps to Reproduce
1. add this code to config/theme.yml of the child theme

```
assets:
  use_parent_assets: true
   css:
     all:
      - id: my-theme-style
        path: assets/css/mystyle.css
        media: all
        priority: 900

```

2. active the debug 
3. See error

**Screenshots**

![11](https://user-images.githubusercontent.com/653230/119800684-4c2d0200-bedd-11eb-8651-032f05899656.png)
![22](https://user-images.githubusercontent.com/653230/119800690-4cc59880-bedd-11eb-9b92-fc6e7f684dd3.png)
![33](https://user-images.githubusercontent.com/653230/119800693-4d5e2f00-bedd-11eb-81f2-a781edd8b9cf.png)
![44](https://user-images.githubusercontent.com/653230/119800697-4e8f5c00-bedd-11eb-8013-a4ed07df7123.png)

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.2

**Comment by hibatallahAouadni** [comment]
Hello @maofree 

Could you please respect and follow the provided template to submit a complete bug report.
And please provide the steps to reproduce :pray: 

Thanks!

**Comment by Maofree** [comment]
done

bye

**Comment by hibatallahAouadni** [comment]
Hello @maofree 

Your issue is due to the unwanted space before "**css**", you code should be as fellow:

```
assets:
  use_parent_assets: true
  css:
    all:
      id: SA4_pure-bio-270
      path: assets/css/theme.css
      media: all
      priority: 900
```

Please check and feedback.
Thanks!
