### ISSUE TITLE
webservice customers - can't create new customers

### ISSUE THREAD

**Issue by pppplus** [PrestaShop/PrestaShop#26568]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Impossible to create new customer via webservices

URL/api/customers?schema=blank gives an error : 
```
<prestashop>
<errors>
<error>
<code>5</code>
<message>
[PHP Notice #8] Trying to access array offset on value of type null (/home/.../public_html/classes/webservice/WebserviceOutputBuilder.php, line 669)
</message>
</error>
<error>
<code>5</code>
<message>
[PHP Notice #8] Trying to access array offset on value of type null (/home/.../public_html/classes/webservice/WebserviceOutputBuilder.php, line 716)
</message>
</error>
</errors>
</prestashop>
```

### Expected behavior

It should done something like : 
```
<prestashop>
 <customer>
  <id/>
  <id_default_group/>
  <id_lang/>
  <newsletter_date_add/>
  <ip_registration_newsletter/>
  <last_passwd_gen/>
  <secure_key/>
  <deleted/>
  <passwd/>
  <lastname/>
  <firstname/>
  <email/>
  <id_gender/>
  <birthday/>
  <newsletter/>
  <optin/>
  <website/>
  <company/>
  <siret/>
  <ape/>
  <outstanding_allow_amount/>
  <show_public_prices/>
  <id_risk/>
  <max_payment_days/>
  <active/>
  <note/>
  <is_guest/>
  <id_shop/>
  <id_shop_group/>
  <date_add/>
  <date_upd/>
  <reset_password_token/>
  <reset_password_validity/>
  <associations>
   <groups>
    <group>
     <id></id>
    </group>
   </groups>
  </associations>
 </customer>
</prestashop>
```

### Steps to reproduce

Create a new customer with webservice
> Originally posted by @ceer (see the [comment](https://github.com/PrestaShop/PrestaShop/pull/29258#issuecomment-1223126475))

Here’s is the way to reproduce the bug
1. Use this docker-compose:

```yaml
version: "3"

services:
  prestashop:
    image: prestashop/prestashop:1.7.8.4-7.4-apache
    environment:
      - DB_SERVER=db
      - DB_NAME=prestashop
      - DB_USER=prestashop
      - DB_PASSWD=prestashop
      - PS_DEV_MODE=0
      - PS_DEMO_MODE=0
      - PS_INSTALL_AUTO=1
      - PS_DOMAIN=localhost:8080
      - PS_FOLDER_ADMIN=admin
      - ADMIN_MAIL=demo@prestashop.com
      - ADMIN_PASSWD=prestashop_demo
    links:
      - db
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - prestashop-net

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
    networks:
      - prestashop-net

networks:
  prestashop-net:
```

2. Enable Webservice in back-office, create a key with all permissions for `customers` ressource
3. Go to http://localhost:8080/api/customers?schema=blank

Results :
```xml
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <errors>
        <error>
            <code>
                <![CDATA[ 5 ]]>
            </code>
            <message>
                <![CDATA[
[PHP Notice #8] Trying to access array offset on value of type null (/var/www/html/classes/webservice/WebserviceOutputBuilder.php, line 669)
]]>
            </message>
        </error>
        <error>
            <code>
                <![CDATA[ 5 ]]>
            </code>
            <message>
                <![CDATA[
[PHP Notice #8] Trying to access array offset on value of type null (/var/www/html/classes/webservice/WebserviceOutputBuilder.php, line 716)
]]>
            </message>
        </error>
    </errors>
</prestashop>
```

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.4
