### ISSUE TITLE
Theme,yml Assets css all customcss child-theme don't work!

### ISSUE THREAD

**Issue by thedarkknight197** [PrestaShop/PrestaShop#26840]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I am editing my child theme,yml to add my custom css file in assets folder but don't work.

My chilt-theme.yml

```
parent: theme_parent
name: theme_parent
display_name: Child theme of theme_parent's theme
version: 1.0.0
assets:
  use_parent_assets: true

  css:
    all:
      - id: my-custom-css
        path: assets/css/modifiche.css
        media: all
        priority: 0
```

### Expected behavior

I expect that my css file located in assets folder will be loaded.
This don't work

### Steps to reproduce

1. Create a child fresh theme from prestashop settings;
2. create a css file in assets folder
3. try to load it with the config i put at the top of this page

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.4.3
