### ISSUE TITLE
Modify doctrine.yml configurations in modules

### ISSUE THREAD

**Issue by thomasDelaporte** [PrestaShop/PrestaShop#29911]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

I currently use `Doctrine` in my modules to make my queries and sometimes I use **MySQL "functions"** like (_ACOS,COS,SIN,RADIANS, etc.._) which are not supported by Doctrine natively.

Theoretically you have to modify the doctrine.yml (app/config/doctrine.yml) config file like this :

```
# Doctrine Configuration
doctrine:
  orm:
   ##...
    dql:
      string_functions:
        regexp: DoctrineExtensions\Query\Mysql\Regexp
      numeric_functions:
        acos: DoctrineExtensions\Query\Mysql\Acos # Added
        cos: DoctrineExtensions\Query\Mysql\Cos # Added
        radians: DoctrineExtensions\Query\Mysql\Radians # Added
        sin: DoctrineExtensions\Query\Mysql\Sin # Added
```

But it is not very clean and problematic if several modules have to do it.

### Describe the solution you'd like

I would like a system where we can extend like our service.yml/routes.yml files.
Or an hook where we could register some DBL function through PHP.

### Alternatives you've considered

PrestaShop add all the DoctrineExtensions available for MySQL.

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.
