### ISSUE TITLE
Allow _legacy_link to be handled via a feature flag

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#29998]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

The migrated controller using Symfony routing usually has a route attribute `_legacy_link` which allows:
- automatic generation of Symfony formatted URL when using `Link::getAdminLink`
- automatic redirection when a legacy URL is used, if a matching route is found then the listener redirects to the Symfony URL

For now the migrated controllers which were not fully released had this route attribute commented. The idea of this feature is to be able to enable this kind of pages via a configurable feature flag.

```yml
admin_attribute_groups_index:
  path: /
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Sell\Catalog\AttributeGroupController::indexAction'
    _legacy_controller: AdminAttributesGroups
    _legacy_link: AdminAttributesGroups
    _legacy_feature_flag: AttributeGroups
```

Then a feature flag which value is `AttributeGroups` needs to be added in the database (in fictures) so that you can choose to toggle the page from the `New & Experimental Features` page.

### Describe the solution you'd like

The legacy redirection is handled in these services:
- `PrestaShopBundle\Routing\Converter\LegacyUrlConverter`
- `PrestaShopBundle\Routing\Converter\RouterProvider`

Two possibilities, either only use the matched route in `getLegacyRouteByAction` from `LegacyRoute` if the associated feature flag is enabled (if not feature flag associated it means it's always enabled).

Or it can be during the generation of the list of LegacyRoute in `getLegacyRoutes` you can filter out the routes which are not enabled, but this method implies refreshing the cache each time a feature flag value is modified.

### Additional context

The new feature flag fixtures are handled here: https://github.com/PrestaShop/PrestaShop/blob/f67c5271cc81ba170878059da2ff356b9417ada9/install-dev/data/xml/feature_flag.xml#L13
The associated wordings can be "stored" here https://github.com/PrestaShop/PrestaShop/blob/ff46766f82ba83470028b0fd1473ccd3f39b77ef/classes/lang/KeysReference/FeatureFlagLang.php#L41

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.
