### ISSUE TITLE
Assets fallback: CDN to Local

### ISSUE THREAD

**Issue by aespasa** [PrestaShop/PrestaShop#30185]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Hello,

It would be great if we could set a fallback to the theme.yml, specyfing a local path instead of a cdn one if our resource is unavailable from the cdn.

E.g:
```yaml
assets:
  css:
    all:
      - id: bootstrap
        path: //cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.2/css/bootstrap.min.css
        fallback: assets/vendor/bootstrap/bootstrap.min.css # Our fallback loaded if our cdn's path isn't available
        priority: 0
        server: remote
```

Is there any feature like that already in place?

I can participate to this feature if required,

Best regards,

### Describe the solution you'd like

Maybe that we can use yepnope.js or an internal custom code to check if the remote resource is available; if not, load our resource specified in the fallback option.

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.
