### ISSUE TITLE
Upgrading Cancel previous steps in the CI

### ISSUE THREAD

**Issue by lartist** [PrestaShop/PrestaShop#30227]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

When we push a new commit the CI is launched and the old jobs are not canceled. There already was an attempting to solve this problem but which doesn't work because there is not enough workers.

### Describe the solution you'd like

Every jobs which is not from the last commit push should be canceled automatically.

### Alternatives you've considered

1) We should upgrade every:
```yaml
- name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
```
to
```yaml
- name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
```

2) We should add this config on every job which is not based on cron

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.
