### ISSUE TITLE
Generate image setting from theme yaml

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#30279]
### User Story

As a merchant, I want to import the default images type of my themes.

### Specs

When the user press import image settings from themes
Then a modal is displayed

Title 'Import images setting of all your themes'
Description 'It will import all the images settings of your theme'
Button 'Cancel' / 'Import'

When the button import is clicked
Then all the images settings of all themes are imported and displays an alert success 'The settings have been successfully updated.'
All the images types from all the configuration yaml file are imported in PrestaShop.

![Image](https://user-images.githubusercontent.com/43613217/201037520-af69e7e4-575b-4ff5-a02e-260233f75583.png)

An image setting already present can't be imported twice.

If none of the themes has image types in the YAML files
Then after clicking import, an error alert is displayed 'Your themes doesn't have image types configured'.

### Acceptance test 

Create store with only humming bird theme
Delete all the images settings

Press import
Then it adds the image settings below:
Note: scope sets on which page the image setting is enabled.

```
image_types:
    cart_default:
      width: 125
      height: 125
      scope: [products]
    small_default:
      width: 98
      height: 98
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 452
      height: 452
      scope: [products, manufacturers, suppliers]
    home_default:
      width: 250
      height: 250
      scope: [products]
    large_default:
      width: 800
      height: 800
      scope: [products, manufacturers, suppliers]
    category_default:
      width: 141
      height: 180
      scope: [categories]
    stores_default:
      width: 170
      height: 115
      scope: [stores]
```
