### ISSUE TITLE
Spike : CQRS2endpoint

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#32338]
For now, we have endpoint like this :

```
resources:
  PrestaShopBundle\Api\Resource\HookStatus:
    operations:
      ApiPlatform\Metadata\Get:
        provider: PrestaShopBundle\Api\StateProvider\HookStatusProvider
        uriTemplate: '/hook-status/{id}'
        requirements:
          id: '\d+'
        exceptionToStatus:
          PrestaShop\PrestaShop\Core\Domain\Hook\Exception\HookNotFoundException: 404
```

The idea is to replace API DTO with QueryResult already exist and create a generic provider. Finally we will be able to create API endpoints match to CQRS with only yml code and integration tests.

Some key points :

- When using command endpoint, maybe we have to send the query result associated
- Replace all value object in query result by scalar values
