### ISSUE TITLE
Migrate Guzzle to HTTPClient

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#32855]
The purpose of this issue is to drop all the usages of guzzle currently used in the core

Instead we should use the Symfony component HTTPClient, but ideally we should introduce a core interface for this client that should be used as the default type in all our code, the actual implementation can be based on the Symfony component but this way we don't couple the core to Symfony directly thus allowing us to switch to any other implementation in the future

Once this is done we should remove Guzzle from our dependencies, this is a breaking change that should be documented The modules that need to use Guzzle will have to either migrate to the new client (recommended) or integrate Guzzle as their dependency

In symfony environment the client should be a service that can be injected via DI

For legacy usages it may be interesting to have a ClientFactory class/service easily reusable in legacy code that will return a client interface (this factory may be used by the DI in Symfony as well)

### Complementary solution

We realized that guzzle is not used directly in the core, but it's used in our circuit breaker library that uses it. So we should first refacto this library to use Symfony client instead. Once it's done and the library is updated in the core (new major version) the guzzle dependency can be removed from composer.

### Update (22/06/2023)

- [ ] Investigate another architecture

Circuit breaker is used only once in the CORE and once in the ps_distributionapiclient module. 
We have to challenged the fact to use it.
Either we still have only one use case in the CORE and we should probably remove it and just use a try catch (which avoid complexity and unnecessary maintenance) or we decide to use it in many use case and then, we should get to the bottom and implement it in these other use cases.

If we decide to still use it, we can replace the guzzle client in prestashop/circuit-breaker by symfony/http-client to avoid loading guzzle for nothing.

Discussed solution/migration:

- new version of circuit breaker library which replaces GuzzleClient with SymfonyHttpClient by default
- at least handle the client options `method` in common
- we keep the `GuzzleClient` for backward compatibility but we should instanciate the actual guzzle client more dynamically
  - remove explicit `use` statements or any other hard dependency on the guzzle library
  - remove guzzle library from the dependency in the circuit break library but keep it as a suggestion
  - to keep using guzzle with recent library you need to explicitly define the client to rely on GuzzleClient and install the library manually on the side
  - the configurations of explicit guzzle should be compatible in version 4.0 and future 5.0

```php
// Manually needed code to keep using Guzzle
$factory->setClient(new GuzzleClient());
```

```yaml
  distributionapiclient.circuit_breaker.settings:
    class: PrestaShop\CircuitBreaker\FactorySettings
    arguments:
      - !php/const PrestaShop\Module\DistributionApiClient\DistributionApi::ALLOWED_FAILURES
      - !php/const PrestaShop\Module\DistributionApiClient\DistributionApi::TIMEOUT_IN_SECONDS
      - !php/const PrestaShop\Module\DistributionApiClient\DistributionApi::THRESHOLD_SECONDS
    calls:
      - setStorage: [ '@prestashop.core.circuit_breaker.storage' ]
      # Additional manual client
      - setClient: [ '@prestashop.manual.guzzle.client' ]
      - setClientOptions:
          - { handler: '@distributionapiclient.circuit_breaker.handlerstack'}
```

**Comment by FabienPapet** [comment]
I  don't think this is a good idea, because the circuit breaker feature is built in inside symfony client, we should discontinue this library instead of migrating it, that would reduce maintenance costs

**Comment by WahbiPS** [comment]
Waiting for discussion between Jo and Pablo

**Comment by MatShir** [comment]
@eternoendless do you have any opinion on the subject ?

**Comment by eternoendless** [comment]
My take on the matter:

* We should avoid doing server side HTTP requests, but when we do, we should continue using Circuit breaker with a fallback. We can't replace timeouts with an exception because if we do, subsequent page loads will need to wait for the service's timeout as well: we know this from experience.
* I'm okay with replacing Guzzle with Sf's HTTP client.
* Our abstraction interface should be Circuit breaker, because low-level HTTP clients don't have an "open" state.
* We can continue to provide Guzzle support on Circuit breaker (in addition to Sf' Http client) for backward compatibility, simply by providing the two clients in the code [here](https://github.com/PrestaShop/circuit-breaker/tree/develop/src/Client). There's the question of how to configure the service depending on PS's version though, because modules targeting older versions will have to configure it using guzzle and newer ones using sf's HTTP client. Creating a new abstraction won't solve this problem.
* For cross-version compatibility, modules should switch to Circuit breaker when possible, or include guzzle themselves if it's a second level dependency (although we know that this puts the module at risk of interference with other modules, so a mitigation strategy should be put in place when doing it)

**Comment by jolelievre** [comment]
Discussed solution/migration:

- new version of circuit breaker library which replaces GuzzleClient with SymfonyHttpClient by default
- at least handle the client options `method` in common
- we keep the `GuzzleClient` for backward compatibility but we should instanciate the actual guzzle client more dynamically
  - remove explicit `use` statements or any other hard dependency on the guzzle library
  - remove guzzle library from the dependency in the circuit break library but keep it as a suggestion
  - to keep using guzzle with recent library you need to explicitly define the client to rely on GuzzleClient and install the library manually on the side
  - the configurations of explicit guzzle should be compatible in version 4.0 and future 5.0

```php
// Manually needed code to keep using Guzzle
$factory->setClient(new GuzzleClient());
```

```yaml
  distributionapiclient.circuit_breaker.settings:
    class: PrestaShop\CircuitBreaker\FactorySettings
    arguments:
      - !php/const PrestaShop\Module\DistributionApiClient\DistributionApi::ALLOWED_FAILURES
      - !php/const PrestaShop\Module\DistributionApiClient\DistributionApi::TIMEOUT_IN_SECONDS
      - !php/const PrestaShop\Module\DistributionApiClient\DistributionApi::THRESHOLD_SECONDS
    calls:
      - setStorage: [ '@prestashop.core.circuit_breaker.storage' ]
      # Additional manual client
      - setClient: [ '@prestashop.manual.guzzle.client' ]
      - setClientOptions:
          - { handler: '@distributionapiclient.circuit_breaker.handlerstack'}
```
