### ISSUE TITLE
Handle legacy page display via the Symfony controller automatically and systematically

### ISSUE THREAD

**Issue by fabienvallon** [PrestaShop/PrestaShop#32981]
**Blocked by https://github.com/PrestaShop/PrestaShop/issues/32980**

### Description

Once #32980 is done and the controller is available we can then remove the principle based on `RouteNotFoundException` in the `index.php` file, any URL even the legacy ones would be handled via Symfony

Some generic route mapping will need to be found to catch the legacy URLs, the URL should not change to avoid breaking changes, it's just that the layout would now be handled by Symfony. This will simplify the work about authentication by Symfony a lot since after this ALL the pages (including the legacy ones) would be handled by the framework.

Example:
```yaml
legacy_controller_route:
  path: /controller={controllerName}
  defaults:
    _controller: LegacyLayoutController::legacyPageAction
```

### Acceptance test

UI tests work fine with symfony layout enabled even on legacy pages

Blocked by https://github.com/PrestaShop/PrestaShop/issues/32980
