### ISSUE TITLE
PS_DEV_MODE does not produce any useful error output

### ISSUE THREAD

**Issue by knipknap** [PrestaShop/PrestaShop#34027]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am trying to debug an error 500 after a fresh auto-install, but even with `PS_DEV_MODE` no useful output is created.
Here is my docker-compose.yml:

```
version: "3.8"
services:
  prestashop:
    image: prestashop/prestashop:8.0-apache
    networks:
      - prestashop
      - traefik-public
    volumes:
      - prestashop-data:/var/www/html
      - prestashop-modules:/var/www/html/modules
      - prestashop-themes:/var/www/html/themes
      - prestashop-override:/var/www/html/override
    environment:
      DB_SERVER: mariadb
      DB_USER: root
      DB_PASSWD: my-custom-password
      DB_NAME: prestashop
      PS_INSTALL_AUTO: 1
      PS_DEV_MODE: 1
      PS_DOMAIN: shop.domain.com
      PS_FOLDER_INSTALL: /install
      PS_FOLDER_ADMIN: shopadmin
      ADMIN_MAIL: mail@gmail.com
      ADMIN_PASSWD: ${ADMIN_PASSWD}
    deploy:
      update_config:
        delay: 10s
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # traefik options omitted

  mariadb:
    image: mariadb
    networks:
      - prestashop
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my-custom-password
      - MYSQL_DATABASE=prestashop

volumes:
  prestashop-data:
    driver: local

  prestashop-modules:
    driver: local

  prestashop-themes:
    driver: local

  prestashop-override:
    driver: local

  mariadb-data:
    driver: local

networks:
  traefik-public:
    external: true
    
  prestashop:
    driver: overlay
```

And here are the last lines of the log of the container:

```
 * No init script found, let's continue...
 AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.0.1.135. Set the 'ServerName' directive globally to suppress this message
 AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.0.1.135. Set the 'ServerName' directive globally to suppress this message
 [Thu Sep 21 16:21:29.111629 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.57 (Debian) configured -- resuming normal operations
 [Thu Sep 21 16:21:29.111666 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
 [Thu Sep 21 16:22:48.650737 2023] [core:alert] [pid 18] [client 10.0.1.9:42410] /var/www/html/.htaccess: RewriteCond: bad flag delimiters
 10.0.1.9 - - [21/Sep/2023:16:22:48 +0000] "GET / HTTP/1.1" 500 808 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
 [Thu Sep 21 16:22:49.084326 2023] [core:alert] [pid 19] [client 10.0.1.9:42416] /var/www/html/.htaccess: RewriteCond: bad flag delimiters, referer: https://shop.domain.com/
 10.0.1.9 - - [21/Sep/2023:16:22:49 +0000] "GET /favicon.ico HTTP/1.1" 500 808 "https://shop.domain.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
```

### Expected behavior

With `PS_DEV_MODE: 1`, a debuggable error message should be shown, not just error 500.

### Steps to reproduce

- Run in docker-compose
- Wait for auto-installation to finish
- Try to access shop or admin page (same result for both)
- Note that only error 500 is shown, nothing to go on for debugging

### PrestaShop version(s) where the bug happened

both 1.7 and 8.0

### PHP version(s) where the bug happened

default

### If your bug is related to a module, specify its name and its version

-

### Your company or customer's name goes here (if applicable).

-
