### ISSUE TITLE
Unable to generate a URL for the named route

### ISSUE THREAD

**Issue by Guervyl** [PrestaShop/PrestaShop#34208]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I'm getting the error 
```
Unable to generate a URL for the named route "isifact_configuration" as such route does not exist.

[Symfony\Component\Routing\Exception\RouteNotFoundException 0]
``` 
using version: prestashop_8.1.2

On versions from 1.7.7 to 8.1.0 the route is working fine. And my module is a Symfony based module.

I ran the command `php bin\console debug:router` and the routes exists. Here is the log:
 ```
isifact_configuration                                         GET|POST         ANY      ANY    /modules/isifact/configuration                                                         

isifact_invoice_emit                                          POST             ANY      ANY    /modules/isifact/invoice/emit/{orderId}
```

Here is the code getting the route:
```
$route = SymfonyContainer::getInstance()->get('router')->generate('isifact_configuration');
Tools::redirectAdmin($route);
```

My route is defined in `config\routes.yml`:
```
isifact_configuration:
  path: /isifact/configuration
  methods: [ GET, POST ]
  defaults:
    _controller: 'Tranzaksyon\Module\Isifact\Prestashop\Controller\DemoConfigurationController::index'
    # Needed to work with tab system
    _legacy_controller: IsifactConfiguration
    _legacy_link: IsifactConfiguration
```

### Expected behavior

It wasn't supposed to say the route does not exist.

### Steps to reproduce

Create a symfony based module.
Define the routes in config\routes.yml
Generate the link using this code:
```
$route = SymfonyContainer::getInstance()->get('router')->generate('isifact_configuration');
Tools::redirectAdmin($route);
```

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1
