### ISSUE TITLE
Docker Nightly : White page (for the BackOffice)

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#35179]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In a new [PR on the `blockwishlist` module](https://github.com/PrestaShop/blockwishlist/pull/236), we use this docker compose file :

```yml
version: '3.7'

services:
  prestashop:
    image: prestashop/prestashop:${PS_VERSION}-apache
    container_name: prestashop
    depends_on: 
      - mysql
    environment:
      - PS_DEV_MODE=1
      - PS_DOMAIN=localhost
      - PS_LANGUAGE=en
      - PS_COUNTRY=fr
      - PS_INSTALL_AUTO=1
      - PS_FOLDER_ADMIN=admin-dev
      - PS_FOLDER_INSTALL=install-dev
      - ADMIN_MAIL=admin@prestashop.com
      - ADMIN_PASSWD=prestashop
      - DB_SERVER=mysql
      - DB_USER=prestashop
      - DB_PASSWD=prestashop
      - DB_NAME=prestashop
    volumes:
      - type: bind
        # Local Path 
        source: ../../
        # Mount Path
        target: /var/www/html/modules/blockwishlist
    ports:
      - 80:80
  mysql:
    image: mariadb:lts
    container_name: prestashop-mysql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '--host=localhost',
          '--user=prestashop',
          '--password=prestashop',
        ]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
      - MYSQL_ROOT_PASSWORD=prestashop
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=prestashop
```

Only the nightly have a white page in BackOffice.

With 8.0.5 & 8.1.3 we have no problems.

### Steps to reproduce

1. Use the `prestashop/prestashop:nightly-apache` image
2. Go to BO
3. The page is white
![f6aa9785bc9c7b8fd40c3f6ede6f59112a939527](https://github.com/PrestaShop/PrestaShop/assets/1533248/feca6c70-f6fa-43a5-9282-f142d427038b)

### PrestaShop version(s) where the bug happened

9.0.x

### If your bug is related to a module, specify its name and its version

docker

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp
