### ISSUE TITLE
#After adding a volume for mysql persistence and executing the rebuild container command, going to the home page of the site again takes me to the installation page again, why?

### ISSUE THREAD

**Issue by stuffren** [PrestaShop/PrestaShop#35675]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

```
version: '3'
services:
  mysql:
    container_name: some-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: some-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_DOMAIN: localhost:8080
    networks:
      - prestashop_network
networks:
    prestashop_network:
```

This is the initial container configuration of the docker-compose.yml file in the root directory of the website in the D:\dockerpro\prestashop root directory of my window host, and I have already successfully installed the prestashop website by executing docker compose up from that directory with the terminal tool.
I can now access the frontend and backend of prestashop successfully.

Then I added the following parameters for the MySQL persistent bindings volume:
```
...
  mysql:
    container_name: some-mysql
    volumes:
      - dbdata:/var/lib/mysql
...
volumes:
  dbdata:
```

**The final configuration is as follows: (mainly for mysql container persistence)：**
```
version: '3'
services:
  mysql:
    container_name: some-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - prestashop_network
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: some-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_DOMAIN: localhost:8080
    networks:
      - prestashop_network
networks:
    prestashop_network:
volumes:
    dbdata:
```

In order to make the docker-compose.yml configuration file take effect, I executed the following commands one after the other:
docker compose down    //Stop and delete existing containers
docker compose up -d    //Start the container using the updated docker-compose.yml file
Then, **I visit http://localhost:8080/ again and the site goes to the installation screen again.**

**Question 1:** Can the official prestashop guys, please help me to see, what is the cause of this?
**Question 2:** Is there any error in the procedure I have stated above?
**Question 3**: Prestashop officials, after you make changes to the docker-compose.yml file, what actions do you usually perform to make the container configuration file take effect?

### Expected behavior

Whenever I update the docker-compose.yml file, instead of prompting me to reinstall, the site allows me to access the frontend and backend of the site normally.

### Steps to reproduce

**1.** In the D:\dockerpro\prestashop directory, create a docker-compose.yml manifest.
version: '3'
services:
  mysql:
    container_name: some-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: some-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_DOMAIN: localhost:8080
    networks:
      - prestashop_network
networks:
    prestashop_network:

**2.In the D:\dockerpro\prestashop directory, through the terminal, execute docker compose up. According to the prompts successfully installed prestashop**

**3. Bind a volume for MySQL persisting, Added the following code：**
...
  mysql:
    container_name: some-mysql
    volumes:
      - dbdata:/var/lib/mysql
...
volumes:
  dbdata:

**4. Run the following commands：**
docker-compose down
docker-compose up -d

When finished executing these two commands, the home page (http://localhost:8080/zh/) of the prestashop website that has just been installed will not open, and the page automatically jumps to the very beginning of the installation interface.

### PrestaShop version(s) where the bug happened

See the docker configuration file

### PHP version(s) where the bug happened

See the docker configuration file

### If your bug is related to a module, specify its name and its version

no
