### ISSUE TITLE
Problem with Hummingbird version

### ISSUE THREAD

**Issue by Codencode** [PrestaShop/PrestaShop#38055]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I was trying out the latest version of the Hummingbird theme, which should be 1.0.0. Here is the link: https://github.com/PrestaShop/hummingbird/archive/refs/tags/v1.0.0.zip

However, when I opened the config/theme.yml file, I saw `version: 0.2.0`

```yml
name: hummingbird
display_name: Hummingbird
version: 0.2.0
author:
  name: "PrestaShop Team"
  email: "pub@prestashop.com"
  url: "https://www.prestashop-project.org/"
```

Am I missing something?

### Steps to reproduce

1. Download the theme from the link: https://github.com/PrestaShop/hummingbird/archive/refs/tags/v1.0.0.zip
2. Check the version number in the config/theme.yml file.

### PrestaShop version(s) where the bug happened

all

### PHP version(s) where the bug happened

Hummingbird template

### Your company or customer's name goes here (if applicable).

@codencode
