### ISSUE TITLE
Permissions issue with prestashop/prestashop docker image

### ISSUE THREAD

**Issue by jouino16** [PrestaShop/PrestaShop#38770]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The same issue has already been raised here, https://github.com/PrestaShop/docker/issues/258 where @PierreRambaud advised to set up user alignment in a Dockerfile (he linked to this example https://github.com/PrestaShop/PrestaShop/blob/develop/.docker/Dockerfile).

The use alignment (or mapping) has to be done in the Dockerfile, as follows:
```
RUN groupmod -g $GROUP_ID www-data \
  && usermod -u $USER_ID -g $GROUP_ID www-data
```

This solution is working maybe in this example https://github.com/PrestaShop/PrestaShop/blob/develop/.docker/Dockerfile which is based on the prestashop/base image (see the [Dockerfile](https://github.com/PrestaShop/PrestaShop/blob/develop/.docker/Dockerfile) code).

But in the case of the prestashop/prestashop image, it does not work. Here is my Dockerfile:
```
FROM prestashop/prestashop:latest

ARG GROUP_ID=1000
ARG USER_ID=1000

# Run files with the same group as the primary user
RUN groupmod -g $GROUP_ID www-data \
  && usermod -u $USER_ID -g $GROUP_ID www-data
```

When I try this Dockerfile file (referenced from a docker-compose.yml) file, I get this error:

![Image](https://github.com/user-attachments/assets/09b1048b-e582-45b2-bc73-f3472d14a77f)

Maybe, this is due to the fact that the PrestaShop files are already created with user 33 (www-data), so creating a directory (mkdir) with the new mapped user 1000 is causing the issue.

As my purpose is to set up a PrestaShop dev/test environment based on WSL2 + Docker Desktop installed on Windows (with the possibility to edit files), here is the workaround (already mentioned [here](https://github.com/PrestaShop/docker/issues/258), but this one is detailed):

- Verify that /var/www/html and its content (PrestaShop files) are owned by www-data:www-data. This should be the case (no action required). If it is not the case, PrestaShop won’t work.
- Verify that container’s files permissions (PrestaShop project files under /var/www/html) are as follows: 775 for directories and 664 for files, which grants the same permissions to www-data group as the www-data user. This should be the case (no action required), as this is how the container installed the PrestaShop files. If it is not the case, then run this on the container’s terminal (should be run as root):
    ```
    find /var/www/html -type d -exec chmod 775 {} \;
    find /var/www/html -type f -exec chmod 664 {} \;
    ```
- Make sure that the /var/www/html directory has 775 permissions. The default permissions are 755. This allows adding the write permission to the group www-data, which allows us to create and delete files at the root level of the PrestaShop project. This can be done either on the WSL2 local mapped folder “`sudo chmod g+w project-folder`” or on the container “`chmod g+w /var/www/html`”, since they are both bound to each other.
- Add local WSL2 user to www-data group: `sudo usermod -aG www-data $(whoami)`.
- That’s it. Now all the mounted PrestaShop files (on the local WSL2 folder) are editable for dev environment.
- Next step is to verify whether we need to make the future files (files that will be created during development) owned by the group www-data. I have to test.

Now you will tell me that this version is for production, use flashlight version instead. Here is my answer:
- Flashlight images work only without volume mapping, so it is useless for developing. I created an issue regarding this: https://github.com/PrestaShop/PrestaShop/issues/38768
- Personally, I prefer working on the production image (prestashop/prestashop) with the possibility to enable XDebug, install Composer and map my local WSL2 user. Why? Because my development (my module for example) will run on a production version, so its development should be done on the same version.

I was able to add Composer and XDebug to the prestashop/prestashop image as follows (Dockerfile content):

```
FROM prestashop/prestashop:latest

ARG INSTALL_XDEBUG=0

# Install composer
RUN php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');" && php /tmp/composer-setup.php --no-ansi --install-dir=/usr/local/bin --filename=composer && rm -rf /tmp/composer-setup.php

# Enable XDebug
RUN if [ "$INSTALL_XDEBUG" = "1" ]; then \
        pecl install xdebug-3.1.3 \
        && docker-php-ext-enable xdebug \
        && echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
        && echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
        && echo "xdebug.client_host=host.docker.internal" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini; \
    fi
```

But, in my humble opinion, it would be great to add 3 environment variables to the prestashop/prestashop image:
- LOCAL_USER: for using mapping if needed. This way the user mapping will work as it will be done at the right moment.
- INSTALL_COMPOSER: whether to install Composer or not. This can contain the version of Composer as a value, instead of 1. This way we can install specific version.
- INSTALL_XDEBUG: whether to install XDebug or not. This can contain the version of XDebug as a value, instead of 1. This way we can install specific version.

### Expected behavior

My suggestion - in my humble opinion, it would be great to add 3 environment variables to the prestashop/prestashop image:
- LOCAL_USER: for using mapping if needed. This way the user mapping will work as it will be done at the right moment.
- INSTALL_COMPOSER: whether to install Composer or not. This can contain the version of Composer as a value, instead of 1. This way we can install specific version.
- INSTALL_XDEBUG: whether to install XDebug or not. This can contain the version of XDebug as a value, instead of 1. This way we can install specific version.

### Steps to reproduce

Run a PrestaShop container using the following files. Please note that the Dockerfile is under ".docker" folder:

docker-compose.yml
```
name: prestashop-8.2.1-custom
services:
    mysql:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: prestashop
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - prestashop-network
    prestashop:
        build:
            context: .
            dockerfile: ./.docker/Dockerfile
            args:
                - INSTALL_XDEBUG=1
        restart: unless-stopped
        depends_on:
            - mysql
        ports:
            - 8070:80
        environment:
            DB_SERVER: mysql
            DB_NAME: prestashop
            DB_USER: root
            DB_PASSWD: admin
            PS_INSTALL_AUTO: 1
            PS_DOMAIN: localhost:8070
            PS_LANGUAGE: fr
            PS_COUNTRY: FR
            PS_FOLDER_ADMIN: admin1234
        volumes:
            - ./ps-821:/var/www/html:rw
        networks:
            - prestashop-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        depends_on:
            - mysql
        ports:
            - 8071:80
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
            PMA_USER: root
            PMA_PASSWORD: admin
        networks:
            - prestashop-network
networks:
    prestashop-network:
volumes:
    db_data:
```

Dockerfile
```
ARG VERSION=latest

FROM prestashop/prestashop:$VERSION

ARG GROUP_ID=1000
ARG USER_ID=1000
ARG INSTALL_XDEBUG=0

RUN groupmod -g $GROUP_ID www-data \
  && usermod -u $USER_ID -g $GROUP_ID www-data

# Install composer
RUN php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');" && php /tmp/composer-setup.php --no-ansi --install-dir=/usr/local/bin --filename=composer && rm -rf /tmp/composer-setup.php

# Enable XDebug
RUN if [ "$INSTALL_XDEBUG" = "1" ]; then \
        pecl install xdebug-3.4.3 \
        && docker-php-ext-enable xdebug \
        && echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
        && echo "xdebug.start_with_request=trigger" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
        && echo "xdebug.client_host=host.docker.internal" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini; \
    fi
```

### PrestaShop version(s) where the bug happened

8.2.1
