### ISSUE TITLE
Fails to Install when Region set to United Kingdom (UK)

### ISSUE THREAD

**Issue by TouchCab** [PrestaShop/PrestaShop#38878]
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

During install of 9.0.0-1.0 basic (the default package from PS Download site), the installation fails at 23% repeatedly.

This happens with PHP 8.1,2,3,4.

While writing this, something crossed my mind, and it appears that it WILL install with Country as US, but NOT as UK. (I need it UK).

Interestingly, the % Completion is different too, in US, creating the DB is at 10%, while for UK, this is 12% of the installation!

The install fails at Create default shop and languages

### Expected behavior

An installation that doesn't fail with UK Selected!

### Steps to reproduce

Download the PS 9 package from Prestashop downloads
Upload to directory and unzip
start the installer by heading to the url of the package
fill in details USING UNITED KINGDOM as the country.
Watch it fail at 23%

NOTE: IT DOES WORK WITH UNITED STATES.

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1, 8.2, 8.3, 8.4

**Comment by SiraDIOP** [comment]
Hello @TouchCab,

Thank you for reporting the issue.
This issue has been reproduced and validated by our QA team.
Test Environment: PS 9.0.0, PHP 8.1
Test Results: Regression 

https://github.com/user-attachments/assets/67e909ae-8e4c-481a-83d7-13097d0e83f9

This issue is now been marked as Verified and Ready.
Thank you

**Comment by TouchCab** [comment]
I am not sure if it is related, but my upgrade just failed from 8.2.1 to 9.0 too, on a UK language only site.

**Comment by vitalijalbu** [comment]
italian too

**Comment by kpodemski** [comment]
the workaround I found is that you can modify `Language::updateMultilangFromClassForShop` and change:

```
$shopDefaultLangId = (int) Configuration::get('PS_LANG_DEFAULT', null, $shop->id_shop_group, $shop->id);`
```

to

```
if (!$shopDefaultLangId) {
            $shopDefaultLangId = $lang->id;
        }
```

I'm still investigating this issue tho.

**Comment by kpodemski** [comment]
I now understand the issue.

The language pack is downloaded automatically when we access the installer. By default, it downloads English or the locale that is detected automatically. The problem arises with the English language, as we primarily download `en-US`, but `en-GB` is not available. During the installation, PrestaShop attempts to install this localization package, but it fails because the process expects at least one language to be available, along with `PS_LANG_DEFAULT`, which is not the case.

The workaround mentioned earlier should be enough to address this issue in the future.

I'll ping @jolelievre and @ibahloul-ps, so that they can take it from there 🫡

**Comment by tswfi** [comment]
This seems to also happen with docker image when running on osx

docker-compose.yml 
```
services:
  mysql:
    image: 'mariadb:latest'
    environment:
        - MYSQL_ROOT_PASSWORD=admin
        - MYSQL_DATABASE=prestashop
    ports:
        - 3306:3306

  prestashop:
    image: 'prestashop/prestashop:9.0.0-1.0-classic'
    ports:
        - 80:80
    environment:
        - PS_DEV_MODE=1
        - PS_INSTALL_AUTO=1
        #- PS_ERASE_DB=1
        - PS_DOMAIN=localhost:3000
        - DB_SERVER=mysql
        - DB_PASSWD=admin
        - DB_USER=root
        - DB_NAME=prestashop
        - ADMIN_MAIL=admin@example.com
        - ADMIN_PASSWD=hunter2hunter3
        - PS_DOMAIN=localhost
        - PS_FOLDER_ADMIN=admin-dev
        - PS_FOLDER_INSTALL=install-dev
    volumes:
        - ./prestashop:/var/www/html:delegated
    depends_on:
        - mysql

```

output from `docker compose up`

```
prestashop-1  | * DB server mysql is available, let's continue !
prestashop-1  | 
prestashop-1  | * Setting up install lock file...
prestashop-1  | 
prestashop-1  | * Reapplying PrestaShop files for enabled volumes ...
prestashop-1  | 
prestashop-1  | * Copying files from tmp directory ...
prestashop-1  | 
prestashop-1  | * No pre-install script found, let's continue...
prestashop-1  | 
prestashop-1  | * Renaming install folder as install-dev ...
prestashop-1  | 
prestashop-1  | * Renaming admin folder as admin-dev ...
prestashop-1  | 
prestashop-1  | * Installing PrestaShop, this may take a while ...
prestashop-1  | 
prestashop-1  | * Launching the installer script...
prestashop-1  | Testing database settings
prestashop-1  | Installing database
prestashop-1  | Dropping database tables
prestashop-1  | Installing default data
prestashop-1  | Truncating database
prestashop-1  | TypeError: LanguageCore::loadAdminTranslatorLocale(): Argument #1 ($locale) must be of type string, null given, called in /var/www/html/classes/Language.php on line 1660 and defined in /var/www/html/classes/Language.php:1670
prestashop-1  | Stack trace:
prestashop-1  | #0 /var/www/html/classes/Language.php(1660): LanguageCore::loadAdminTranslatorLocale(NULL, false)
prestashop-1  | #1 /var/www/html/classes/Language.php(1640): LanguageCore::updateMultilangFromClassForShop(Object(AttributeGroupLang), Object(Language), Object(Shop))
prestashop-1  | #2 /var/www/html/classes/Language.php(1573): LanguageCore::updateMultilangFromClass('ps_attribute_gr...', 'AttributeGroupL...', Object(Language))
prestashop-1  | #3 /var/www/html/classes/Language.php(1547): LanguageCore::updateMultilangTables(Object(Language), Array)
prestashop-1  | #4 /var/www/html/classes/Language.php(1407): LanguageCore::updateMultilangTable('gb')
prestashop-1  | #5 /var/www/html/classes/Language.php(1224): LanguageCore::installLanguagePack('gb', NULL, Array)
prestashop-1  | #6 /var/www/html/src/PrestaShopBundle/Install/Install.php(614): LanguageCore::downloadAndInstallLanguagePack('gb')
prestashop-1  | #7 /var/www/html/src/PrestaShopBundle/Install/Install.php(1250): PrestaShopBundle\Install\Install->{closure:PrestaShopBundle\Install\Install::installLanguages():613}()
prestashop-1  | #8 /var/www/html/src/PrestaShopBundle/Install/Install.php(613): PrestaShopBundle\Install\Install->callWithUnityAutoincrement(Object(Closure))
prestashop-1  | #9 /var/www/html/src/PrestaShopBundle/Install/Install.php(453): PrestaShopBundle\Install\Install->installLanguages(Array)
prestashop-1  | #10 /var/www/html/install-dev/controllers/console/process.php(243): PrestaShopBundle\Install\Install->installDefaultData('PrestaShop', 'GB', 0, true)
prestashop-1  | #11 /var/www/html/install-dev/controllers/console/process.php(163): InstallControllerConsoleProcess->processInstallDefaultData()
prestashop-1  | #12 /var/www/html/install-dev/classes/controllerConsole.php(139): InstallControllerConsoleProcess->process()
prestashop-1  | #13 /var/www/html/install-dev/index_cli.php(60): InstallControllerConsole::execute(17, Array)
prestashop-1  | #14 {main}
prestashop-1 exited with code 1

```

Latest version of docker 

```
$ docker -v
Docker version 28.1.1, build 4eba377
```

and os x

```
$ sw_vers
ProductName:		macOS
ProductVersion:		15.5
BuildVersion:		24F74
```
